### ISSUE TITLE
False advertisement, Needle will (NOT) automagically prepend it.

### ISSUE THREAD

**Issue by sw0o0sh** [tomas/needle#105]
```javascript
needle.get('google.com/search?q=syd+barrett', function(err, resp) {
  // if no http:// is found, Needle will automagically prepend it.
});
```

```javascript
needle.get('google.com/search?q=http+status+codes', function(err, resp) {
  // Needle does NOT automagically prepend it, OUCH!!
});
```

Seems like false advertisement to me, owner refuses to fix bug whilst maintaining his cute internet boy-charm and smiley-faces. Since the owner does not care about his logical errors within his code, I request that this snippet be pulled from the README as it is clearly false advertisement, OUCH!!

**Comment by misterhat** [comment]
OUCH indeed. I'm surprised that this was ignored even with perfectly valid examples of it being a bug.

**Comment by tomas** [comment]
@sw0o0sh Ouch, so now it's personal? Looks like you had a rough week. Why don't you go grab a beer? It's friday night.

**Comment by sw0o0sh** [comment]
Sorry, I am not a neglectful alcoholic tomas. Please stop advertising broken features, and take responsibility.

**Comment by misterhat** [comment]
How you feel about sw0o0sh or whatever mishap you two have gotten yourselves into doesn't affect the validity of the bug. Please just fix it one way or another :(

**Comment by tomas** [comment]
@misterhat I certainly will. But only once this guy stops throwing shit at me.

**Comment by misterhat** [comment]
@tomas I wouldn't let emotions get in the way of the righteous path of bug-free code.

**Comment by tomas** [comment]
@misterhat Tomorrow will be another day. :)

**Comment by sw0o0sh** [comment]
Everyone is welcome to use my patched version @
https://www.npmjs.com/package/thorn

**Comment by sw0o0sh** [comment]
Everyone is welcome to use my patched version @
https://www.npmjs.com/package/thorn
