### ISSUE TITLE
Socket hangup on multiple async requests

### ISSUE THREAD

**Issue by monitz87** [tomas/needle#110]
Hi, I'm having a socket hangup issue whenever I try to do many simultaneous requests (over 100 for example). I've researched the issue and apparently setting http.globalAgent.maxSockets to 'Infinity' should fix this. I think the optimal way to handle this is to add the maxSockets option to needle, even though it's quite specific. I am aware that node.js version 0.12 comes with 'Infinity' sockets by default, but still it would be a nice addition in my opinion.

**Comment by tomas** [comment]
Hi @monitz87, 

You're right. In the meantime I guess nothing prevents you from doing `http.globalAgent.maxSockets = Infinity` in your code. I don't think it's a good idea to include that on Needle and force everyone to a specific number of maxSockets.
