### ISSUE TITLE
GET request with body

### ISSUE THREAD

**Issue by godspeedelbow** [tomas/needle#112]
I know it's not standard practice, but it's allowed and makes sense in certain situations.

Would this be something to consider?

http://stackoverflow.com/questions/978061/http-get-with-request-body

**Comment by tomas** [comment]
Hmm. In which situation would it make sense?

**Comment by godspeedelbow** [comment]
Good question. I had a pretty GET call with quite a few params from one
backend service to the other. I figured there was a max size to the url
length (and therefore I needed to pass them along in the body). Actually,
that's just a browser limitation (if I'm not mistaken), so I implemented it
as query params anyways.

You can close this issue :)

**Comment by tomas** [comment]
Cool, thanks man.
