### ISSUE TITLE
Post is displaying debug info

### ISSUE THREAD

**Issue by blakemcbride** [tomas/needle#113]
When I do a post, I am seeing:

    Making request #1 { protocol: 'http:',
      host: 'localhost',
      port: '9200',
      path: '/components-1427228775787',
      method: 'post',
      headers: 
       { Accept: 'application/json',
         Connection: 'close',
         'User-Agent': 'Needle/0.8.2 (Node.js v0.12.0; linux x64)',
         'Content-Type': 'application/json',
         'Content-Length': 102,
         Host: 'localhost:9200' } }
       Got response { 'content-type': 'application/json; charset=UTF-8',
          'content-length': '21' }

The post function is printing this to the console.  Can it be turned off?

Thanks.

Blake McBride

**Comment by tomas** [comment]
You're probably setting a DEBUG env var. This will be removed once we replace the current inhouse debugging system for the `debug` module itself.

**Comment by blakemcbride** [comment]
blake@blake-Dell-M6800 ~ $ echo $DEBUG

    blake@blake-Dell-M6800 ~ $ 

No DEBUG set.  I am running it through WebStorm & node.

Thanks.

Blake

**Comment by tomas** [comment]
That's odd. What do you get with?

`node -e "console.log(process.env.DEBUG)"`

Anyway, I just pushed Needle v0.9.0 that replaces the current console.log with the `debug` module. You should no longer have this problem.

**Comment by blakemcbride** [comment]
blake@blake-Dell-M6800 ~/Downloads $ node -e "console.log(process.env.DEBUG)"
    undefined
    blake@blake-Dell-M6800 ~/Downloads $

**Comment by tomas** [comment]
Then I guess there's some other module that's putting that env variable before Needle checks for its presence. Did you try 0.9.0?

**Comment by blakemcbride** [comment]
It isn't there.

    blake@blake-Dell-M6800 ~/ComponentServer $ npm update needle
    needle@0.8.2 node_modules/needle
    └── iconv-lite@0.4.7
    blake@blake-Dell-M6800 ~/ComponentServer $ 

Thanks for all the help!

**Comment by tomas** [comment]
Try with:

`npm install needle@0.9.0 --save`

**Comment by blakemcbride** [comment]
That fixed everything.  Thanks a lot!
