### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by blakemcbride** [tomas/needle#114]
Hi.  In your README.md, under neadle.request(), the API is defined as taking 5 arguments but the example shows it taking 4.  THE API doesn't show any arguents as optional [].  

Thanks.

Blake

**Comment by tomas** [comment]
Oh, yes, the options argument is optional.

**Comment by blakemcbride** [comment]
In your README.md, it would be great if the optional arguments had [ and ] around them so we know which ones are optional.  I noticed this is a problem with most of your API listings.

**Comment by tomas** [comment]
Will do. Thanks for the reminder!

**Comment by tomas** [comment]
The documentation does say, though, that both the options and the callback are optional. :)

`All of Needle's request methods return a Readable stream, and both options and callback are optional.`
