### ISSUE TITLE
request('get'...) can't pass json data

### ISSUE THREAD

**Issue by blakemcbride** [tomas/needle#115]
Network traffic see with curl:

    GET /components/_search HTTP/1.1
    User-Agent: curl/7.35.0
    Host: localhost:9200
    Accept: */*
    Content-Length: 386
    Content-Type: application/x-www-form-urlencoded
    {
        "from": 0,
        "size": 20,
        "query": {
                "bool": {
                    "must": [
                        {"match_phrase_prefix" : {
                            "classifications" : "passive_components/resistors"
                        }},
                        {"match" : {
                            "_all" : "1000"
                        }}
                    ]
                }
            }
        }

With needle:

JS Code:

        var options = {
            json: true
        };
        var host = 'http://' + esHost + '/' + path;
        needle.request('get', host, json, options, callback);

Resulting network traffic:

    GET /components/_search?from=0&size=20&query[bool][must][0][match_phrase_prefix][classifications]=passive_components%2Fresistors&query[bool][must][1][match][_all]=1000 HTTP/1.1
    Accept: */*
    Connection: close
    User-Agent: Needle/0.9.0 (Node.js v0.12.0; linux x64)
    Host: localhost:9200

Thanks.

Blake

**Comment by tomas** [comment]
Looks like you're just passing "true" as the options. Try with:

```

var options = {
        json: true
    };
    var host = 'http://' + esHost + '/' + path;
    needle.get(host, options, callback);
```

**Comment by blakemcbride** [comment]
In your example, where is my json data?

**Comment by tomas** [comment]
Oh, now I see. When passing data to a GET request, Needle builds a query string and appends it to the URL, given that those requests should not contain a body.

**Comment by blakemcbride** [comment]
Yea.  Whatever you are doing isn't working for me.  I am trying to pass json data through a get.  Just FYI, CURL works, and the 'request' npm package works too.

**Comment by tomas** [comment]
Why _would_ you want to send a body as part of a GET request anyway? You might want to suggest the developer of that endpoint to stick to the spec. Needle doesn't send bodies on GET requests because there's a very high chance that the server on the other side won't even mind to read it.

**Comment by blakemcbride** [comment]
Tell that to elasticsearch  
http://www.elastic.co/guide/en/elasticsearch/guide/current/multi-query-strings.html

**Comment by monolithed** [comment]
+1, It will be very useful for many API and more elegant than:

```
import needle from 'needle';
import url from 'url';

let href = url.parse('https://google.com');

href.query = {
	foo: 1,
};

href = url.format(href);

needle.get(href, (error, response) => {
   // ... 
});
```

**Comment by tomas** [comment]
Closing this issue, as this was implemented long ago.

![screenshot 2016-06-06 at 10 33 15 pm](https://cloud.githubusercontent.com/assets/10574/15846960/c374a294-2c36-11e6-981b-0d9adde8e4b9.png)
