### ISSUE TITLE
unknown domain: inc.com

### ISSUE THREAD

**Issue by OKNoah** [tomas/needle#116]
I'm trying to do the following with this `url`: http://inc.com/gene-marks/the-one-way-to-tell-if-you-re-a-successful-entrepreneur.html?cid=sf01001

	var data = needle.get( url, { 
		compressed: true,
		follow_max: 5
	}, function ( error, response ) {

When I do that, the `response.body` is:

    '\n<html>\n<head>\n<title> inc.com</title>\n</head>\n<body>\nunknown domain: inc.com</body></html>'

**Comment by tomas** [comment]
That's odd. What do you get with curl?

**Comment by OKNoah** [comment]
It's a 301 redirect

**Comment by tomas** [comment]
I can take a look at this later today. In the meantime, you can try enabling debugging and see if that helps to find out what the problem is.

**Comment by OKNoah** [comment]
Thanks a lot. If you want some context check out the issue I mentioned above: https://github.com/tmpvar/jsdom/issues/648

Someone suggested using Needle to decompress before passing to JSDOM, but I get this problem when I do.

**Comment by OKNoah** [comment]
Did you get any insight into this problem?

**Comment by tomas** [comment]
Yup! I found out what the problem is. Pushing the fix in exactly 183 seconds.

**Comment by OKNoah** [comment]
Thank you!

**Comment by uzumakinaruto123** [comment]
@tomas 

It's 2020 :p but I am facing this


```
needle('get', url, {
                json: true,
                headers: headers,
            })
            .then((res) => console.log(res.statusCode)) // 301
            .catch((err) => console.log(err));
```

I can confirm that the same endpoint with the same config works if I do it with Axios, Postman, Insomnia!


In the logs, I can see some HTML saying Redirecting URL to exact same URL
