### ISSUE TITLE
deflateRaw support

### ISSUE THREAD

**Issue by BiteBit** [tomas/needle#117]
coffee-script
```
needle = require 'needle'
needle.get 'http://www.youku.com', compressed: true, (error, resp, body)->
  console.log error
  console.log body
```
zlib error when i get youku.com
http headers content-encoding is 'deflate' and i use zlib.deflateRaw can success

**Comment by tomas** [comment]
Thanks for the heads up. I'll take a look at this in a while.

**Comment by tomas** [comment]
It looks like you'll need to turn off compression for the time being. It looks like the `youku.com` guys decided not to follow the spec and forget about the zlib headers in the deflated body, as described [here](http://stackoverflow.com/questions/3932117/handling-http-contentencoding-deflate).

A possible option is to implement some option like `decompressor` that allows you to say something like `decompressor: 'inflateRaw'`. But that might take a while.

**Comment by BiteBit** [comment]
to compatible with complex environment, i solve it  by call inflateRaw after inflate error

**Comment by tomas** [comment]
I'm not sure I undertand. Can you share an example in code?

**Comment by servo1** [comment]
testing with needle.js line 43    decompressors['inflateRaw']   = zlib.Inflate;
Added this as a potential solution if this is what you were talking about @tomas 

Any pointers in implementing error handling that doesn't kill the app would be great - where to add a try and catch statement?

**Comment by tomas** [comment]
Hi @servo1 and sorry for the long delay.

You mean error handling on the output stream? 

```
var needle = require('needle')
var resp = needle.post('server.com', { ... });

resp.on('error', function(err) { 
  console.log('Holy mac!', err);
})

resp.on('end', function() {
  console.log('Response finished');
})
```

**Comment by tomas** [comment]
I'm not really sure if we can do something about this, so I'm closing this issue for the time being. @servo1 if there's a way to fix it feel free to reopen it later.
