### ISSUE TITLE
Set-Cookie header with multiple cookies only saves the last one

### ISSUE THREAD

**Issue by Narzerus** [tomas/needle#118]
This is a very dangerous bug as it is hard to notice while working with needle,
I think #111 fixes this though I haven't tested it:

If a request returns multiple cookies in the headers like this:

`Set-Cookie: foo=1; bar=2`

`res.cookies` will equal: `{bar: 2}` the reason behind this has to do with `parse()` at `lib/cookies` where the result format does not allow for more than one cookie to be stored and therefore it is replaced:

```javascript
// if key is part of valid_keys, set it, otherwise set it as key=[key] and value=[val]
  for (var key in obj) {
    if (valid_keys.indexOf(key.toLowerCase()) != -1) {
      res[key]  = obj[key];
    } else {
      res.key   = key; // <-- THIS
      res.value = obj[key];
    }
  }
```

Since #111 treats this parsing different I think it might fix this issue

**Comment by tomas** [comment]
Really? Well, I always said cookie support was still experimental. Does it also happen on #111?

**Comment by Narzerus** [comment]
Yup, just tested it, its still present there sadly

**Comment by jorgeaguirre** [comment]
In fact this is not a bug, the problem resides in that you are using a incorrect syntax, the second key/value (`bar=2`) is an attribute of (`foo=1`):
````
Set-Cookie: foo=1; bar=2
````
The correct syntax for setting multiple cookies is this
````
Set-Cookie: <name1>=<value1>; Attrs...
Set-Cookie: <name2>=<value2>; Attrs...
...
````

**Comment by Narzerus** [comment]
I looked into RFC6265 and you are correct, I quote:

```
An origin server can include multiple
   Set-Cookie header fields in a single response.  The presence of a
   Cookie or a Set-Cookie header field does not preclude HTTP caches
   from storing and reusing a response.

   Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
   a single header field.  The usual mechanism for folding HTTP headers
   fields (i.e., as defined in [RFC2616]) might change the semantics of
   the Set-Cookie header field because the %x2C (",") character is used
   by Set-Cookie in a way that conflicts with such folding.
```

Closing this issue as this is actually expected behavior.

**Comment by trhme** [comment]
This does not work for me with Chrome:

```
Set-Cookie: <name1>=<value1>; Attrs...
Set-Cookie: <name2>=<value2>; Attrs...
...
```

When I do that it Chrome only accepts the last one.  However, if the case of the Set-Cookie is different, then it will accept both.  So this would work for me (notice the case of the c):

`Set-Cookie: <name1>=<value1>; Attrs...
Set-cookie: <name2>=<value2>; Attrs...
...`
