### ISSUE TITLE
Testability issues

### ISSUE THREAD

**Issue by Narzerus** [tomas/needle#119]
I don't mean to flood this repo with issues, but I cloned needle to try make some fixes myself and I'm having a hard time testing as it does not work out of the box. 

Could you provide some basic instructions on setting up the local environment for testing? It would be great to have out-of-the-box testabilty as it makes it easier for contributors to submit good PRs, lowers the risk of merging bad code and allows you to add CI integration (which also helps a lot as it rejects PRs right away when tests are not passing).

I see that you are running a local server to test needle, you think this could be replaced by an http mocking library?

**Comment by tomas** [comment]
$ git clone https://github.com/tomas/needle.git
    $ npm install
    $ npm test

What error are you getting?

**Comment by Narzerus** [comment]
Welp, it tries to load some cert files which are not present in the repo

**Comment by tomas** [comment]
Oh, yes, I forgot. You need to generate the SSL keys inside `test/keys`.

   $ mkdir -p test/keys
   $ openssl genrsa -out test/keys/ssl.key 2048
   $ openssl req -new -key test/keys/ssl.key -x509 -days 999 -out test/keys/ssl.cert

**Comment by tomas** [comment]
Ok, I just updated the documentation. Thanks for the heads up.

**Comment by Narzerus** [comment]
any time!
