### ISSUE TITLE
timeout vs open_timeout

### ISSUE THREAD

**Issue by jarzuaga** [tomas/needle#125]
Hi,

I'm not sure if this is an issue or me misreading the docs. I have a post to a service which takes about a minute to respond back. I noticed I was getting a "socket hang up" error when using needle on my nodejs app, but not through postman. I tried setting the open and read timeout options to 0 with no luck. Then I looked at needle's code and noticed a setting of "timeout: 10000" on a defaults object, so I tried "timeout" instead of open_timeout on my options object and that worked. Am I reading the docs wrong?

**Comment by tomas** [comment]
What version are you using? From version 0.8 the `timeout` option acts as an alias for `open_timeout`, given that we added `read_timeout` a few releases later. Versions lower that 0.8 don't handle `open_timeout` as an option -- just `timeout`.

**Comment by jarzuaga** [comment]
That explains it then. I'm using version 0.7.2. I'll update then. Two questions:
1) Is version 0.9 backward compatible with code written with 0.7?
2) What's new on version 0.9? I see the version is tagged but there's no release with info on what the version introduces/fixes.

Anyways, this can be closed. Many thanks!

**Comment by tomas** [comment]
Oh that's just lazy me. I just pushed an added the relevant bits. Let me know if you need anything else!

**Comment by tomas** [comment]
And yes, unless very duly noted, needle will always remain backwards compatible. The only major change so far was the streams2 refactor that allowed needle to be called without a callback.

**Comment by jarzuaga** [comment]
Great, thanks!
