### ISSUE TITLE
Posting a very long string

### ISSUE THREAD

**Issue by mrft** [tomas/needle#126]
Posting a very long string prints this error a few times.

<pre>warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.<pre>

**Comment by tomas** [comment]
Example code?

**Comment by mrft** [comment]
In my case it is a batch post to a couchdb instance

<pre>
var requestOptions = {
		username: "username",
		password: "password",
		json: true,
		timeout: 10 * 60 * 1000 //10 minutes
}
//very big string > 32M characters
bulkString = '{	"all-or-nothing": true, "docs": [{<doc1>}, {<doc2>}, ...]}'

needle.post( <https-url>, bulkString, requestOptions, mycallback )
</pre>

**Comment by tomas** [comment]
I'm performing a test with a string of `33554432` bytes and unable to replicate this error. What version of Node.js are/were you using? :)

**Comment by mrft** [comment]
I think that it was the same as I have now: v0.10.25 (but I am not 100%
sure).

Long time ago...



2015-10-16 4:03 GMT+02:00 Tomás Pollak <notifications@github.com>:

**Comment by tomas** [comment]
[This commit](https://github.com/tomas/needle/commit/fb57c6da116fc77c69dcda14af7d8cbfd50a9898) fixes this issue (and there's a test that verifies it), so closing this one!
