### ISSUE TITLE
example of specifying name parameter for multipart file upload 

### ISSUE THREAD

**Issue by starpause** [tomas/needle#127]
I'm trying to specify the ```name``` parameter for a multipart upload being performed with needle. I can see the variable being set in ```generate_part()``` of ```multipart.js``` but can't trace it back up the chain or find any examples. Any clues greatly appreciated, TIA!

**Comment by starpause** [comment]
I got it! Multipart ```name``` parameter is taken from the keys in ```data``` object. Example:

```
	var data = {
	  stringYouWantNameToBe: { file: './22AT_Commands.pdf', content_type: 'application/pdf'}
	}
```

**Comment by tomas** [comment]
Cool! Let me know if you have other questions.
