### ISSUE TITLE
Allow passing function to supplement redirect options

### ISSUE THREAD

**Issue by terinjokes** [tomas/needle#132]
I have more advance redirection requirements that can't be mapped nicely to the current "follow_*" options. In the future, I would like to be able to pass a function to supplement the `should_follow` method.

**Comment by tomas** [comment]
What kind of requirements do you have? (Just to have an idea)

**Comment by terinjokes** [comment]
I'd like to be able to do a lookup to see if the redirection is allowed from the current location.

**Comment by tomas** [comment]
I'd be happy to merge this into master if you're up for some hacking. :)
