### ISSUE TITLE
Protocol relative URLs

### ISSUE THREAD

**Issue by monolithed** [tomas/needle#135]
And according to RFC 2396 (URI Syntax) and RFC 2616 (HTTP 1.1) these URI starting with two slashes are valid.

This notation is often used to avoid the "mixed content" problem.

```js
needle.get('//www.google.com', function (error, response) {
	console.log(error, response);
});
```
```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' } undefined
```

**Comment by tomas** [comment]
I think this is happening because of [this](https://github.com/tomas/needle/blob/master/lib/needle.js#L242-L243). It should be an easy fix.

**Comment by monolithed** [comment]
A better way:

```
import url from 'url';

let href = url.parse('//google.com');

if (!href.startsWith('//') && !href.protocol) {
	href.protocol = 'https'
}

console.log(url.format(href));
```

**Comment by matthewmueller** [comment]
why is the default https? afaik protocol-relative refer to loading assets on a page that share the root url's protocol.

**Comment by tomas** [comment]
I agree with @matthewmueller. Assuming https will likely not work.

**Comment by monolithed** [comment]
Sorry guys, its a typo )

**Comment by matthewmueller** [comment]
actually, assuming any protocol won't necessarily work.

**Comment by tomas** [comment]
Done. ce22c53

**Comment by monolithed** [comment]
Yup. However, I can give an example which cause some pain for me

```js
import Xray from 'x-ray';
import needle from 'needle';

let xray = Xray();

let get_links = new Promise((resolve, reject) => {
	needle.post('http://example.com', {
		foo: 'bar'
	},
	(error, response) => {
		if (error) {
			reject(error);
		}
		else {
			xray(response.body, {
				links: ['.links']
			})
			((error, result) => {
				if (error) {
					reject(error);
				}
				else {
					resolve(regions); 
				}
			});
		}
	});
});

get_links.then(links => {
	for (let link of links) {
		xray(link, {
			foo: '.foo'
		})
		((error, result) => {
			console.log(result); // I never get here
		});
	}
});
```

```
>> Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```

**Comment by tomas** [comment]
I don't see what's wrong with your example @monolithed. You _are_ throwing that exception after all, right?

**Comment by tomas** [comment]
I'm closing this issue for the moment, by the way. Feel free to open a new one if you want me to address something else.
