### ISSUE TITLE
Parsing additional MIME types as XML

### ISSUE THREAD

**Issue by lovett** [tomas/needle#136]
Is there a way to specify the MIME types that trigger XML parsing?

I wanted to parse an RDF file, but it's not one of the types specified in `lib/parsers.js`. I can do something like this:

```
var needleParsers = require('needle/lib/parsers');
needleParsers['application/rdf+xml'] = needleParsers['text/xml'];
var needle = require('needle');
```

But wondered if there's a better way.

Adding another export to `parsers.js` could work, but might be a hassle to keep updating over time.

**Comment by tomas** [comment]
Seems like rdf+xml should be added to the list of parseable XML content types. Thanks for the heads up and sorry for the late response!
