### ISSUE TITLE
Get final url after redirect

### ISSUE THREAD

**Issue by lucaswxp** [tomas/needle#137]
I'm trying to get the final redirected URL of a http request, but I can't find it anywhere.

I tried inspect `resp.req`, but also couldn't find anything. Is this information available?

Regards

**Comment by herlon214** [comment]
:+1:

**Comment by tomas** [comment]
Needle's return object is a emitter that triggers a 'redirect' event whenever it occurs.

``` 
var url = 'foobar.com', 
      last_url = url;

var req = needle.get(url, { follow_max: 3 }, function(err, resp) {
  console.log('last URL requested was: ' + last_url);
})

req.on('redirect', function(url) {
  last_url = url;
})
```

**Comment by lucaswxp** [comment]
Thanks @tomas! That's very helpful.

**Comment by thebarty** [comment]
Just noting that storing the result in a global variable is not really a good idea with an async function. I mean, multiple threats can overwrite the value and it will lead to wrong results... 

does anyone have an async solution for this?

**Comment by thelinuxlich** [comment]
is it possible to obtain the last url using await needle()?
