### ISSUE TITLE
Debugging messages not selective

### ISSUE THREAD

**Issue by gregt590** [tomas/needle#138]
I am attempting to use the network.get_public_ip() function from your network package with uses needle to perform its function.  I also use the debug package (see npm package debug) through out my code with different modules names [for example via debug = require('debug')('app:awsintf')], as is used in express and other Node.js packages, so I can selectively turn on different debugging messages as needed.

Unfortunately needle is re-using debug's DEBUG environment variable which control's which debugging traces are enabled such that if I enable any, I can't turn off needle's debugging  messages to console.log.

Please either use a different environment variable, or follow the debug packages convention and only turn on your debugging messages if an appropriate string (like "needle") is found in the DEBUG environment variable value.

Thanks,
Greg

**Comment by tomas** [comment]
Try updating needle to the latest version. Needle doesn't use the DEBUG env variable [any more](https://github.com/tomas/needle/commit/be20f7b36e9c91c68d84c60f6b47fdc9068e3420#diff-ce47d3711808893008d0d794d3ede7bc).
