### ISSUE TITLE
File corrupted

### ISSUE THREAD

**Issue by herlon214** [tomas/needle#140]
The code above download a rar file, and then extract him using the unrar, but sometimes the file came corrupted (I already checked it's ok with the file).

```javascript
    var stream = needle.get(url, {headers: headers, "follow_max": 5});
    stream.pipe(out);
    stream.on('end', function() {
      extract();
    });
```

Any idea?

**Comment by tomas** [comment]
Can you share the URL of the RAR you're downloading so I can test?

**Comment by herlon214** [comment]
Here is the url: http://insubs.com/d/Xggr8
(You must set Referer to: http://insubs.com/l/zenr7)

2015-08-18 15:39 GMT-04:00 Tomás Pollak <notifications@github.com>:

> Can you share the URL of the RAR you're downloading so I can test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomas/needle/issues/140#issuecomment-132328488>.
>



-- 
*Att, Herlon Aguiar*

**Comment by tomas** [comment]
I finally took the time to test this and you're right! (Sorry for taking so long).

I'll keep on testing and let you know what I find out.

**Comment by herlon214** [comment]
Thanks Tomás, I'm waiting

Em quinta-feira, 1 de outubro de 2015, Tomás Pollak <
notifications@github.com> escreveu:

> I finally took the time to test this and you're right! (Sorry for taking
> so long).
>
> I'll keep on testing and let you know what I find out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomas/needle/issues/140#issuecomment-144879714>.
>


-- 
*Att, Herlon Aguiar*

**Comment by tomas** [comment]
Got it! Pushing a fix in a few minutes.

**Comment by herlon214** [comment]
Thanks a lot!! 😄

Em quinta-feira, 1 de outubro de 2015, Tomás Pollak <
notifications@github.com> escreveu:

> Got it! Pushing a fix in a few minutes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomas/needle/issues/140#issuecomment-144884230>.
>


-- 
*Att, Herlon Aguiar*

**Comment by sigod** [comment]
@tomas 
Did you forget to add `out.on('end', ...` or it isn't needed?
