### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by noamokman** [tomas/needle#141]
The module checks for any value in the debug env var.
Instead of these lines:
```js
    debugging   = !!process.env.DEBUG,
    debug       = debugging ? console.log : function() { /* noop */ };
```

Please use [debug](https://www.npmjs.com/package/debug).
It was made for this purpose.

Would you like me to PR?

**Comment by tomas** [comment]
Needle [already uses](https://github.com/tomas/needle/blob/master/lib/needle.js#L13) debug -- that's an old piece of code right there. Please update needle!
