### ISSUE TITLE
Parsing XML response stopped to work

### ISSUE THREAD

**Issue by PainKKKiller** [tomas/needle#142]
Did it on this way
```javascript
var logoptions = {
    parse_response: true,
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', }
}

 var data = { username: user, password: pass };
    needle.post(global.config.kayako_staff_api_url + "?/Core/Default/Login", data, logoptions, function (err, resp) {
        console.log(resp.statusCode);
        console.log(resp.body); //Here the problem!

        if (err) {
            console.log(err);
        }
     
    });


```
Responce of the server (resp.body) comes in XML, and it was parsed in JSON. Everything worked fine, but suddenly (I nothing changed in code) in resp.body I started to get raw XML. No problem I can parse it on my own. But I really have no idea why it happened.

**Comment by PainKKKiller** [comment]
Some additional imformation. It happened when I deleted from project some unused modules (crypto-js, json2xml and something else). After that parsing by needle stopped to work.

**Comment by tomas** [comment]
Hi, 

You problably also removed the `xml2js` module which needle depends on (but doesn't explicitly require) for XML parsing. Just `npm install xml2js --save` and violá!
