### ISSUE TITLE
error event sometimes emitted

### ISSUE THREAD

**Issue by lperrin** [tomas/needle#145]
From what I understand, needle should always pass an error to the callback and never emit an `error` event.

However, I've processed in production crash with an ETIMEOUT error. I've been able to reproduce it locally.

It seems to happen when the host is unreachable. It's a simple GET request and I pass the following options:

```
var defaultOptions = {
  timeout: 5000,
  read_timeout: 5000,
  rejectUnauthorized: false
};
```

The extended stack trace I get:

```
message connect ETIMEDOUT
stack Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at afterConnect (net.js:896:19)
---------------------------------------------
    at Readable.on (_stream_readable.js:708:33)
    at http.js:1754:12
    at process._tickDomainCallback (node.js:492:13)
---------------------------------------------
    at ClientRequest.onSocket (http.js:1731:11)
    at new ClientRequest (http.js:1433:10)
    at exports.request (https.js:123:10)
    at Needle.send_request (/Users/laurent/dev/front/node_modules/needle/lib/needle.js:373:26)
    at Needle.start (/Users/laurent/dev/front/node_modules/needle/lib/needle.js:291:15)
    at exports.(anonymous function) (/Users/laurent/dev/front/node_modules/needle/lib/needle.js:581:61)
    at exports.listMessagesSince (/Users/laurent/dev/front/server/connectors/facebook/facebook.js:134:11)
    at FacebookPump._poll (/Users/laurent/dev/front/server/pumps/facebook/facebook_pump.js:75:12)
    at listOnTimeout (timers.js:121:15)
---------------------------------------------
```

**Comment by tomas** [comment]
Can you share the code you're using so I can reproduce the error?

**Comment by lperrin** [comment]
Not easily, but I've added logs everywhere in my local copy of needle, so I'll be able to provide more info soon.

**Comment by lperrin** [comment]
OK, I've been able to reproduce the problem once (but it took several hours). From what I see, I get a socket timeout after you remove the 'error' handler.

I get first an `ECONNRESET` which is correctly reported by needle, followed by a `ETIMEDOUT` which is not caught.

I should also have mentioned that I'm still on node.js 0.10.40, so it might be a node.js bug. Would you accept a PR that would basically do `request.on('error', function() {});` after you remove the real handler?

```
set error handler
remove error handler
set error handler
remove error handler
set error handler
needle timeout
had_error
remove error handler
{ [Error: socket hang up] code: 'ECONNRESET' }
Fri Oct 09 2015 19:13:50 GMT-0700 (PDT) #error# facebook - Poll error with inbox: 2, company: front
data { status: 'internal_error',
  reason: 'socket hang up',
  source: 'facebook',
  accountStatus: 'offline',
  errorType: 'facebook_unreachable' }
reason Poll error with inbox: 2, company: front
Fri Oct 09 2015 19:13:50 GMT-0700 (PDT) #info# facebook-pump - Account status set to offline (errorType: facebook_unreachable) (inbox 2).
Fri Oct 09 2015 19:14:04 GMT-0700 (PDT) #critical# domain-pump - error performing inbox (2) action bump_last_sync
message connect ETIMEDOUT
stack Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at afterConnect (net.js:896:19)
---------------------------------------------
    at Readable.on (_stream_readable.js:708:33)
    at http.js:1754:12
    at process._tickDomainCallback (node.js:492:13)
---------------------------------------------
    at ClientRequest.onSocket (http.js:1731:11)
    at new ClientRequest (http.js:1433:10)
    at exports.request (https.js:123:10)
    at Needle.send_request (/Users/laurent/dev/front/node_modules/needle/lib/needle.js:378:26)
    at Needle.start (/Users/laurent/dev/front/node_modules/needle/lib/needle.js:291:15)
    at exports.(anonymous function) (/Users/laurent/dev/front/node_modules/needle/lib/needle.js:587:61)
    at exports.listMessagesSince (/Users/laurent/dev/front/server/connectors/facebook/facebook.js:134:11)
    at FacebookPump._poll (/Users/laurent/dev/front/server/pumps/facebook/facebook_pump.js:75:12)
    at listOnTimeout (timers.js:121:15)
---------------------------------------------
    at /Users/laurent/dev/front/server/pumps/facebook/facebook_pump.js:63:27
```

**Comment by tomas** [comment]
Hmm, that's odd. I'm pretty sure if you get a ECONNRESET error you shouldn't get more errors on `request`. Once the request is done the listener is removed on [this line](https://github.com/tomas/needle/blob/master/lib/needle.js#L354). 

If indeed the `request` object is able to emit more than one error then I we should definitely remove or change that behaviour. However I do need to be able to reproduce the error, so it would greatly help to see an example bit of code that provokes it. :)

**Comment by lperrin** [comment]
Sorry, but it's not that easy to isolate this part of the code. It's a very large codebase and the issue only happens ~once a day. Basically, my code polls a Facebook endpoint every 10s.

I've added more logs to track exactly which request is emitting the error.

I had a crash today that looks like this. It shows that request 125 is emitting an error after you remove the error handler.

```
remove error handler:  124
{ [Error: socket hang up] code: 'ECONNRESET' }
Mon Oct 12 2015 13:44:35 GMT-0700 (PDT) #error# facebook - Poll error with inbox: 2, company: front
data { status: 'internal_error',
  reason: 'socket hang up',
  source: 'facebook',
  accountStatus: 'offline',
  errorType: 'facebook_unreachable' }
reason Poll error with inbox: 2, company: front
Mon Oct 12 2015 13:44:35 GMT-0700 (PDT) #info# facebook-pump - Account status set to offline (errorType: facebook_unreachable) (inbox 2).
set error handler 125
needle timeout 125
had_error socket hang up 125
remove error handler:  125
{ [Error: socket hang up] code: 'ECONNRESET' }
Mon Oct 12 2015 13:45:00 GMT-0700 (PDT) #error# facebook - Poll error with inbox: 2, company: front
data { status: 'internal_error',
  reason: 'socket hang up',
  source: 'facebook',
  accountStatus: 'offline',
  errorType: 'facebook_unreachable' }
reason Poll error with inbox: 2, company: front
spurious error from 125
message connect EHOSTUNREACH
stack Error: connect EHOSTUNREACH
```

Here's the relevant part in your code:

```javascript
var requestCount = 0;

Needle.prototype.send_request = function(count, method, uri, config, post_data, out, callback) {

  var timer,
      returned     = 0,
      self         = this,
      request_opts = this.get_request_opts(method, uri, config),
      protocol     = request_opts.protocol == 'https:' ? https : http;

  var requestId = requestCount++;

  function done(err, resp, body) {
    if (returned++ > 0) return;

    if (timer) clearTimeout(timer);
    console.log('remove error handler: ', requestId);
    request.removeListener('error', had_error);

    request.on('error', function (err) {
      console.log('spurious error from', requestId);
      throw err;
    });

    if (callback)
      callback(err, resp, body);
    else
      out.emit('end', err, resp, body);
  }

  function had_error(err) {
    console.log('had_error', err.message, requestId);
    debug('Request error', err);
    done(err || new Error('Unknown error when making request.'));
  }
```

**Comment by lperrin** [comment]
To be more accurate: we simply poll the same URL every 10s on a laptop with an unstable connection (limit of range Wi-Fi).

**Comment by tomas** [comment]
Have you ran your code with `NODE_DEBUG=http`? That will surely help debug what's going on behind the curtains. [This is](https://github.com/nodejs/node/blob/master/lib/_http_client.js#L238) the relevant section in Node.js's http_client.js -- the line that triggers the timeout error.

I've been adding a few tests under [errors_spec.js](https://github.com/tomas/needle/blob/master/test/errors_spec.js), trying to replicate the behaviour but so far no luck. Are you triggering requests using setInterval or setTimeout after each one finishes?

**Comment by tomas** [comment]
I'm now thinking that we might be better by removing the line that removes the error handler. I just did a test trying to replicate #126 and I'm getting a EPIPE error, even though the request has already finished and the node process is not really piping to anywhere.

**Comment by tomas** [comment]
Ok I think I have it. Take a look at the [errors](https://github.com/tomas/needle/compare/errors) branch.

**Comment by lperrin** [comment]
OK, I'm running the new branch. I'll tell you tomorrow if the crash still occurs.

**Comment by lperrin** [comment]
I think I still have the crash even in the errors branch. I've restarted everything with debug activated.

**Comment by tomas** [comment]
Any news about this?

**Comment by tomas** [comment]
Ok, closing. I think the recent changes to needle.js should take care of this.
