### ISSUE TITLE
When combining needle package with async.auto, performance will degrade when there are a lot of concurrency requests

### ISSUE THREAD

**Issue by mcchin** [tomas/needle#148]
When I do something like below:

    router.get('/test', function(req, res) {
        async.auto({
            step1: function(cb) {
                console.log('step1');
                cb();
            },
            step2: ['step1', function(cb) {
                needle.get('https://www.google.com', function(err, response, body) {
                    console.log('needle return');
                });
                cb();
            }]
        }, function(err) {
            res.json({
                'return': 'here'
            });
        });
    });

Average API response time is 800ms - 900ms

I tested with ab benchmark, as the problem is only obvious when there are a lot of concurrent requests
ab -n 100 -c 25 https://test.server.com/test

But if I have changed from needle.get to request.get or http.get, average response time is 10ms - 30ms
Also if I have changed from async.auto to async.series, the average response time is 10ms - 30ms as well.

Something weird is going on if I use aync.auto with needle like above.

Any ideas?
Thanks

**Comment by tomas** [comment]
Hmm, interesting. Have you tried passing different values for async.auto's `concurrency` param?

**Comment by mcchin** [comment]
I have tried 0, 1, 9, it doesn't feel much difference as majority of the respond time is around 800ms -900ms

**Comment by mcchin** [comment]
I have tried on async@1.5.0 (with concurrency param - no value, 0,1,9), async@0.9.0 (without concurrency param). The results are similar

**Comment by tomas** [comment]
What happens if you increase the number of maxSockets? Say:

````
require('http').globalAgent.maxSockets = 1000
```

What Node version are you running?

**Comment by mcchin** [comment]
I am using v0.10.37
Results are similar when I have applied maxSockets = 1000.

I have tested on another machine which is running v0.12.2, results are similar as well

**Comment by tomas** [comment]
Hmm, the plot thickens.

What does async.auto do differently than async.series? Do you think some kind of deadlock may be ocurring?

**Comment by mcchin** [comment]
Basically I have no idea, the current work around is that I replace needle with request or other http get package. But I have a lot of places using needle, so I am hoping there is a more simpler solution then updating my entire code base to use different package.

**Comment by tomas** [comment]
Of course. Does async.parallel behave like .auto or like .series, in this case?

**Comment by mcchin** [comment]
Hmm...you might be onto something.

async.series - ok (10 - 30ms)
async.parallel - slow (800ms - 900ms)
async.auto - slow (800ms - 900ms)

**Comment by tomas** [comment]
OK, I'm going to try a few things with async and see where I get. 

What happens if you put the callback in step two inside the actual needle callback? (as I assume you'd expect the endpoint to behave).

**Comment by mcchin** [comment]
I have tried putting async callback inside needle callback, and outside of needle. Both yield similar results.

Thanks for your support!

**Comment by tomas** [comment]
I think I found something, but I'm not sure it's related. Try passing `{ connection: 'keep-alive' }` to the needle.get options.

**Comment by mcchin** [comment]
Wow, this definitely affect the performance, that does the trick!
