### ISSUE TITLE
Is it possible using Needle?

### ISSUE THREAD

**Issue by efkan** [tomas/needle#150]
I have to modify the incoming request  and forwarding to another URL. After this point, client has to see the new URL in his address bar and HTML content of the new URL.

For instance adding an updating date to the request body like the following;

![routing diagram](https://cloud.githubusercontent.com/assets/6974198/11264562/395e6360-8e9d-11e5-882c-6ecf369a265d.png)

Would it be possible? 

ps: The scenairo completely fictitious. I need to use other important data instead of updating date that are should stay as secret. This operations can be performed on ASPX (by using hiddenfields) or JSP pages that are run on the server side. But Node.js is different.

**Comment by tomas** [comment]
Of course this is possible. I'm not sure how this fits as an "issue" in the needle repo, though. I'm sorry but I'm closing it.
