### ISSUE TITLE
Cookie parsing exceptions

### ISSUE THREAD

**Issue by pierreliefauche** [tomas/needle#151]
While parsing `set-cookie-string`, [`var res = COOKIE_PAIR.exec(str);`](https://github.com/tomas/needle/blob/master/lib/cookies.js#L45) [can return an array or `null`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec). 
In case it returns `null`, an exception is thrown by [`res[KEY_INDEX]`](https://github.com/tomas/needle/blob/master/lib/cookies.js#L48).

Also, `decodeURIComponent` used to decode `res[KEY_INDEX]` can throw an exception as well.

Maybe these exceptions could be caught and either trigger an error on the request or just discard the invalid cookie.
If they are not caught, may an option to disable cookie parsing altogether be useful?

**Comment by tomas** [comment]
Good point. Can you share an example that provokes this exception?

I do think it's a good idea to allow disabling cookie parsing (being false the default option). It might be a performance win on some situations.

**Comment by pierreliefauche** [comment]
Yes, here are a few examples I ran into (inputs to `parseSetCookieString` function):

- empty string
- `HttpOnly;Secure`
- `language_Ryan USA=1; path=/`

**Comment by tomas** [comment]
Hey @pierreliefauche -- sorry for the delay. Are you up for a PR?

**Comment by HazeDevelopment** [comment]
This still ongoing? I have the problem too..
(empty string)

**Comment by tomas** [comment]
Ok, just fixed this error and pushed a new version to npm. Can you try it and see if it works?
