### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [tomas/needle#152]
Would you please create a LICENSE (or LICENSE.md) file with your copyright information and the text of the MIT license?  The MIT license requires that the text of the license accompany the source code.  It also makes life easier for Linux distributions that want to package up the software.

**Comment by tomas** [comment]
Sure, will do. Thanks for the heads up.

**Comment by tomas** [comment]
Done: https://github.com/tomas/needle/blob/master/license.txt
