### ISSUE TITLE
Version number being read from package.json

### ISSUE THREAD

**Issue by lededje** [tomas/needle#154]
https://github.com/tomas/needle/blob/master/lib/needle.js#L24

This breaks when trying to zip up code for distribution, for example aws lambda.

Any way around this?

**Comment by tomas** [comment]
What specific error are you getting?

**Comment by tomas** [comment]
By the way, we used to use JSON.parse(fs.readFileSync()) but that was [recently changed](https://github.com/tomas/needle/commit/f7a72f18ad554b2416471134834aaed950f32ee4) precisely to allow bunding with browserify.

**Comment by lededje** [comment]
You are totally right; I was running an older version. Thanks for your help! Closing...

**Comment by tomas** [comment]
:)
