### ISSUE TITLE
Version 1.0.0 Changes

### ISSUE THREAD

**Issue by corbinu** [tomas/needle#157]
1.0.0 was recently released on NPM but the changes do not appear to be here.

Just wondering if there were any breaking changes?

Thanks

**Comment by tomas** [comment]
Nothing breaking, but two things to watch out: the [removal of Connection: close](https://github.com/tomas/needle/commit/06d8c71de16f85ac210c5a001f85b21d598ab2ca) if running node > 0.11.4, which should make multiple requests to a server run much faster, and secondly, a few changes to the way post bodies [can be set](https://github.com/tomas/needle/commit/98b2fec4dd960473c98da0e2cf50c0f2c9ac5c16) through parameters.

I hope to update the documentation this week.
