### ISSUE TITLE
What about custom agent that support tunelling throught proxy?

### ISSUE THREAD

**Issue by cloudever** [tomas/needle#158]
This is awesome and lightweight lib for http, I begun use it after request.js
Is it possible to add feature for tunelling throught proxy via CONNECT request? 
Or how use it if exists. I didn't find something in the code.

Thanks.

**Comment by tomas** [comment]
The issue in #177 shows an example using a tunnelling proxy. Is that what you need?

(Sorry for the delay, by the way)

**Comment by tomas** [comment]
This doesn't seem like an issue so I'm closing it. If there's something that's not working as expected feel free to open up a new one.
