### ISSUE TITLE
Aborting the needle request

### ISSUE THREAD

**Issue by kotofond** [tomas/needle#159]
Normally, in order to abort the request I use the following technique:
```
var stream = needle.get(url, options);
...
stream.request.abort();
```
However I've noticed when Needle starts following redirects I'm no longer able to abort the request using `stream.request.abort()` and it keeps redirecting till the end. So I was wondering if there's a better way of aborting requests?

**Comment by tomas** [comment]
Hmm, looks like a bug. Can you share the code you're using so I can reproduce the behaviour?

Thanks for reporting, by the way.

**Comment by kotofond** [comment]
Many thanks for the prompt response.
I've just been trying to compose a code sample to reproduce the issue and discovered that Needle actually works perfectly fine and the issue is entirely my fault.
In case if anyone encounters the same problem:
As opposed to what I've stated in my first comment my actual code looked like this:

```
var stream = needle.get(url, options);
var savedRequest = stream.request;
...
savedRequest.abort();
```
So saving request in a different variable caused the issue because `savedRequest.abort()` aborts the original request, not the one that is following redirection

**Comment by tomas** [comment]
Haha, no problem. 

Anyway, I do think Needle should offer a way to abort the request directly (like stream.abort()) without having to go though stream.request.

**Comment by kotofond** [comment]
Yes, that would be handy :+1:
