### ISSUE TITLE
conflicts with the debug module

### ISSUE THREAD

**Issue by contra** [tomas/needle#160]
When you're using this with debug, it always logs and you can't turn it off.

**Comment by tomas** [comment]
I think there's else going on there. How are you running your script?

**Comment by contra** [comment]
@tomas The problem is that the debug module uses the DEBUG env var to control it.

For example, `DEBUG=app:* node app.js` will trigger logging from this module because it only checks if DEBUG exists.

I think an easy resolution for this is to use a different env var (NEEDLE_DEBUG?) or maybe use the debug module, which is really cool.

**Comment by tomas** [comment]
Ah, I see. You're not using the latest version, it's that simple. Needle does use the debug module now.

`npm install needle@1.0.0`

**Comment by contra** [comment]
nice - this is a dependency of a dependency so ill get them to update

thanks!
