### ISSUE TITLE
Needle version 1.0.0 is not working for chunked S3 download

### ISSUE THREAD

**Issue by ranjansumit** [tomas/needle#163]
I tried chunked download with needle 0.7.11, it was working fine. Then i upgraded to needle 1.0.0 and its failing. File size is 10.2 MB and I am trying to download it in chunks using s3. while doing so somewhere its failing. I was not able to find the reason for failure. But its because of needle 1.0.0. My observation is there is some problem in the redirect.

**Comment by tomas** [comment]
@ranjansumit What specific error are you getting? Can you share the snippet the code you're using to get the file?

**Comment by tomas** [comment]
Ping @ranjansumit
