### ISSUE TITLE
Make request with opts

### ISSUE THREAD

**Issue by UrielMys** [tomas/needle#166]
Hello, i would like for needle to be able to make the request with just an  options object and the callback. Right now I'm using the following code:

```
        var options = {  
            hostname: hostname,  
            port: config.port,  
            method: config.method,  
            path: config.endpoint,  
            headers: config.headers  
        }  
        var req = http.request(options, function(response) {
            response.setEncoding('utf8');
            options.statusCode = response.statusCode
            var str = '';
            response.on('data', function(chunk) {
                str += chunk;
            });
            response.on('end', function() {
                options.response = str;
                registerRequest(str);
            });
        })
        req.on('error', function(error) {
            console.log(error)
        })
        req.end();
```

The idea i have is to be able to make it on needle in the same way the http library does

Thank you!

**Comment by tomas** [comment]
You can call [needle.request](https://github.com/tomas/needle#needlerequestmethod-url-data-options-callback) and pass the verb you with to send, in addition to the options and/or callback function. The options are different, obviously. 

Is that what you need?

**Comment by UrielMys** [comment]
No, needle.request requires that i send not only the method but also the url where im going to make the request to.  
The idea is to be able to send the port, headers, etc and let the needle library do the request

**Comment by UrielMys** [comment]
What i mean is being able to make the request using the same options object, since the port might not be sent and making the url dynamically would mean doubling up the work (once by my app and once by the library)

**Comment by tomas** [comment]
How would you call this function, then? Something like this?

```js
  var http_opts = { hostname: 'server.com', ... };
  needle.request({ timeout: 1000, parse: 'xml', http: http_opts }, function(err, resp) {
    // ... 
  })
```
