### ISSUE TITLE
Charset detection not default as utf-8

### ISSUE THREAD

**Issue by inDream** [tomas/needle#170]
In https://github.com/tomas/needle/blob/master/lib/needle.js#L109, 
`var charset = 'iso-8859-1', arr = header.split(';');`
Is there any reason to default charset as Latin-1 not utf-8?

As some server may not return charset at header,
wrong charset is detected when handling not ASCII character,
and change it to `utf-8` solved the problem.

I can create a pull request if you don't mine.

**Comment by tomas** [comment]
As far as I'm aware the default charset according to the W3C is still 8859-1. I'm aware the HTML5 standard changed it to UTF-8 but last time I checked it still wasn't present in the official spec.
