### ISSUE TITLE
About file stream POST issue

### ISSUE THREAD

**Issue by VitoWen** [tomas/needle#173]
I tired to use needle v1.0.0 to POST file to my server:

```
var opts = {headers:{'file_name': 'test'}}; 
needle.post(serverUrl, fs.createReadStream(fileSrc), opts, function (err, resp, body) {
    if (err) {
        console.log('[U3D] error: ', err);
    }
    callback();
});
```

But i check the file size is zero byte on my server.
So, i downgrade needle to v0.10.0 and used the same code to POST file to my server again.
I found my server can receive a complete file.
What is difference between v1.0.0 and v0.10.0 for file stream POST?
Or should i add other opts with v1.0.0?

**Comment by skyerh** [comment]
I have a same issue of this

**Comment by tomas** [comment]
Hey guys, I'll take a look at this later today!

**Comment by VitoWen** [comment]
I found if i add the opts as below i can receive the complete file in my server:
```
var opts = {
  headers:{
    'file_name': 'test'
  },
  json: true
}; 
```
Needle v1.0.0 always set the Content-type to 'application/json; charset=utf-8' or 'application/x-www-form-urlencoded'. 
```
if (!config.headers['Content-Type']) {
  config.headers['Content-Type'] = options.json
  ? 'application/json; charset=utf-8'
  : 'application/x-www-form-urlencoded'; // no charset says W3 spec.
}
```
In my original case, i didn't set the json of opts. Needle v1.0.0 will set the Content-type to 'application/x-www-form-urlencoded' by default. 
But i don't understand why the content-type:  'application/json; charset=utf-8' can apply with file stream POST?

**Comment by tomas** [comment]
@VitoWen What kind of file are you trying to transfer? I just did a small test and it worked as expected.

**Comment by tomas** [comment]
It'd also help to see what code you're using on the server to process the request.

**Comment by VitoWen** [comment]
I send a general doc file(about 75 KB) to my server.
Below is my server information:
Node version: v0.12.2
```
exports.needleHandler = function (req, res) {
  async.auto({
      save_file: function (cb) {
          var saveTo = path.join(savePath, path.basename(fileName)),
              ws = fs.createWriteStream(saveTo);
          ws.on('close', function () {
             console.log('Done');
             cb();
          });
          req.pipe(ws);
      }
  }, function final(err) {
       ...
  });
};
```
Or do you have other better method to receive the file?

**Comment by tomas** [comment]
It looks like this has been fixed, or there was a bug somewhere else in your code. I just tested the following snippet and I get the expected result:

```
var http   = require('http');
var needle = require('needle');
var fs     = require('fs');
var async  = require('async');

var server = http.createServer(function(req, res) {
  async.auto({
    save_file: function (cb) {
      var saveTo = './output', 
              ws = fs.createWriteStream(saveTo);

      ws.on('close', function () {
         res.end('Thanks.');
         cb();
      });

      req.pipe(ws);
    }
  }, function final(err) {
    console.log('File size:', fs.statSync('/tmp/foo').size);
  });

}).listen(3000);

var opts = { headers: {'file_name': 'test'} };
var data = fs.createReadStream(process.argv[2]);

needle.post('localhost:3000', data, opts, function (err, resp, body) {
  console.log(err || 'Got a ' + resp.statusCode);
  server.close();
});

```
