### ISSUE TITLE
Store redirect cookies in res.cookies object

### ISSUE THREAD

**Issue by rchipka** [tomas/needle#174]
When `follow_set_cookies` and `parse_cookies` is true, shouldn't all of the redirect cookies also appear in the final `res.cookies` object?

Right now, only cookies set on the final request are parsed and stored in `res.cookies`.

**Comment by rchipka** [comment]
Would a PR implementing a fix for this be accepted?

**Comment by tomas** [comment]
Yeah, sure. Can you describe a scenario here before implementing it, though, so we can analyze and make sure it makes sense?

**Comment by tomas** [comment]
Hold on, this is already waiting to be merged here: https://github.com/tomas/needle/pull/129

I'll take a look at it now and get it merged.
