### ISSUE TITLE
HTTPS requests fail with proxy

### ISSUE THREAD

**Issue by bisubus** [tomas/needle#176]
I'm testing `needle` https request through local Node proxy with this:

```
'use strict'

const needle = require('needle');

needle
.get('https://play.google.com/store', { proxy: 'http://127.0.0.1:3128' }, (err, res) => {
    if (err)
        console.error('err', err);
    else
        console.log(res.statusCode, res.body.toString());
});
```

With [pure `http` proxy implementation](https://gist.github.com/bisubus/d1e68da4a72b894c24d38ddb732dca62#file-pure-http-example-js) it gets

> `301 '<HTML>\n<HEAD>\n<TITLE>Moved Permanently</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Moved Permanently</H1>\nThe document has moved <A HREF="https://play.google.com/store">here</A>.\n</BODY>\n</HTML>\n'`

With [`http-proxy` proxy implementation](https://gist.github.com/bisubus/d1e68da4a72b894c24d38ddb732dca62#file-http-proxy-example-js) (self-signed certs) it gets

> `404 '<!DOCTYPE html><html><head><meta http-equiv="content-type" content="text/html;charset=utf-8"><link rel="shortcut icon" href="//ssl.gstatic.com/android/market_images/web/favicon_v2.ico"><title>Not Found</title>\n <...>`

With [`proxy` implementation](https://gist.github.com/bisubus/d1e68da4a72b894c24d38ddb732dca62#file-proxy-example-js) it gets

> `400 'Only "http:" protocol prefix is supported\n'`

due to [this](https://github.com/TooTallNate/proxy/blob/v0.2.3/proxy.js#L200-L205).

The implementations may not be perfect, but `request` is ok with all of the above, so do wget and the browsers.

The problem doesn't affect http requests, `needle` is ok with all of the proxies.

Windows 7
Node 6.2.0 x64
needle 1.0.0

**Comment by tomas** [comment]
Is this a problem with needle or with the proxy implementations you mentioned, then?

**Comment by bisubus** [comment]
@tomas I believe this is a problem with Needle. I've also had problems with non-local proxies. Node proxies are mentioned for problem reproduction, the variety of errors may suggest what exactly is wrong.

The problem disappears when custom proxy-enabled HTTP Agent is used together with Needle (e.g. [`proxy-agent`](https://www.npmjs.com/package/proxy-agent)).

**Comment by tomas** [comment]
I believe `request` has a very thorough implementation of proxy handling, whereas in Needle it's just a few lines of code. I'd be happy to get a fix merged as long as we're not rewriting `request`... you know, the point of Needle is to have a clean and lean HTTP client.

Are you up for submitting a PR with a fix? :)

**Comment by bisubus** [comment]
I don't have an opportunity to take care of this now, but look forward to this. Btw, `got` followed the path of least effort and [just delegated proxy functionality to third-party agents](https://github.com/sindresorhus/got#proxies).

**Comment by tomas** [comment]
I documented this solution (which I like) in the readme so I'm closing this one.
