### ISSUE TITLE
Error when using tunnel agent with proxy, and credentials are not valid

### ISSUE THREAD

**Issue by cloudever** [tomas/needle#177]
I wrote this code for tunnel agent
`
this.tunnelingAgent = tunnel.httpsOverHttp({
        proxy: {
            host: parseProxy.hostname,
            port: parseProxy.port,
            proxyAuth: parseProxy.auth //incorrect
        },
        headers: {
            'Connection': 'Keep-Alive'
        },
        rejectUnauthorized: false
    });
`

and this for needle 
`
var options = { 
...
agent: this.tunnelingAgent
}
`

If proxy auth credentials are incorrect then error throws on line 374 in the needle.js (core)
`request.socket.removeListener('end', on_socket_end);` 
and write

> Cannot read property 'removeListener' of null

If proxy auth credentials are correct then all works fine.
Maybe it need some checks if proxy connection was failed and socket not exist..

Needle v1.0.0

**Comment by tomas** [comment]
Oh, good point. This means that request.socket does not exist, right? Seems like an easy fix.

**Comment by tomas** [comment]
How could we check whether the proxy connection failed?

Can you share a snippet of code so I can reproduce the error?

**Comment by tomas** [comment]
Ping @cloudever

**Comment by cloudever** [comment]
Hi. Sorry, I can't just share it, currently I'm using local fork of your needle lib

**Comment by tomas** [comment]
There was a fix for the socket listeners a while ago, so I'm closing this one. Feel free to reopen it if you find anything!
