### ISSUE TITLE
Raise condition: ECONNRESET

### ISSUE THREAD

**Issue by frankred** [tomas/needle#179]
Currently running into a very strange behaviour. We have a integration test based on ```mocha``` and ```needle``` that only occurs sometimes. We just call a nodejs API url  (written with ```express```) with ```needle``` and analyse the response body. Sometimes we got the following error:

```
Uncaught Error: read ECONNRESET
      at exports._errnoException (util.js:870:11)
      at TCP.onread (net.js:552:26)
```

It seems that this error occurs more often on slower machines. On local (very fast) machine 1/10, on slow jenkins machine 6/10. 

If we run into this problem the needle call that causes the ```ECONNRESET``` do not reach the express route. So on the node side we do not receive anything.

If we access the API through a loadbalancer than this problem does not occur, but if we talk directly to this nodes we sometimes get this error.

I've tried to reproduce this problem with other http clients (e.g. POSTMAN) but everything worked well.

Does anybody know or have a idea where this problem has his origin?

```js
    it.only("[GET] /", function (done) {

        this.timeout(timeout);

        var test = function (endpoint, cb) {
            debug('get ' + endpoint.host);
            console.log("\t" + endpoint.host + "/");
            needle.get(endpoint.host + "/", function (err, res) {
                var msg = JSON.stringify(endpoint);
                assert.ifError(err, msg);
                assert.ok(res, msg);
                assert.equal(res.statusCode, 200);
                assert.ok(res.body.name, msg);
                assert.ok(res.body.description, msg);
                assert.ok(res.body.version, msg);
                assert.ok(res.body.cluster, msg);
                assert.ok(res.body.hostname, msg);
                assert.ok(res.body.doc, msg);
                assert.ok(res.body["suppilo-api"], msg);
                cb();
            });
        };

        async.mapSeries(endpoints, test, function (error) {
            assert.ifError(error);
            done();
        });
    });
```

**Comment by tomas** [comment]
Hi,

Are you running 1.0.0? Does this also occur if using 0.11?

**Comment by frankred** [comment]
Tried it with both versions and the same behaviour. Do you know what could be a problem? Maybe the symbiosis with async.

**Comment by mindnuts** [comment]
@frankred Can you please update if your issue was fixed? You did not mention anything here before closing this issue. I am getting the same error so was curios.

**Comment by frankred** [comment]
Sorry did not found any solution for this problem. 
Have you tried the `request` lib if this error still occurs?
