### ISSUE TITLE
dependencies are not installed

### ISSUE THREAD

**Issue by clayzermk1** [tomas/needle#180]
### Environment
node 0.10.46
npm 3.10.5
needle 1.0.0

### What happened?
`Error: Cannot find module 'xml2js' from '<project path>/node_modules/<nested dependency>/node_modules/needle/lib'`
needle is a dependency of a nested module but its dependencies were not installed during an `npm install` in my project path. I had to execute an `npm install` inside the needle directory of the dependency tree to get everything to work.

### What did you expect to happen?
I expected the necessary dependencies to be installed from a high level `npm install`.

### Thoughts
I recently updated to npm 3.10.5, before I was using 3.9.x and didn't have this problem I don't think.
I `rm -rf`'d my node_modules directory and then did a `npm install` before this error occurred.

Any help is greatly appreciated. Thank you for your time and such a great library! It's my go-to!

**Comment by tomas** [comment]
That's weird. If you don't have the `xml2js` dependency it shouldn't explode -- Needle should simply disable the XML parser. [Here's](https://github.com/tomas/needle/blob/master/lib/parsers.js#L52-L54) the relevant piece of code.

Do you know if npm 3.10 changed in any way the logic upon which modules are required/loaded?

**Comment by clayzermk1** [comment]
I know, right? I figured I'd try here first in case anyone had seen this problem already.

I just took a look at the 3.10.x release notes, there's a lot going on in there. It's entirely likely to me that one of the refactors in 3.10 has caused this.

I'll experiment with different npm versions to try and narrow it down.

**Comment by clayzermk1** [comment]
This is my bad. Needle is glorious and wonderful.

I had added a node module to my browserify bundle, the package `resolve` was trying to require xml2js which wasn't installed and exploded.

Nothing to see here. Thank you for your time @tomas!

**Comment by thecristen** [comment]
Is there a recommended resolution to this? I am running into precisely the same problem (albeit in a webpack context)
