### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by knksmith57** [tomas/needle#182]
Heya, it's been a few months since the last release and a few important commits have landed since then.

When you have a chance, can we please get a new version and release to npm? Should only take a few minutes.

Thanks!

**Comment by tomas** [comment]
Will do! Thanks for the heads up. :)

**Comment by tomas** [comment]
Done! Documenting the release as we speak.

**Comment by knksmith57** [comment]
Thanks for the quick turn around on this one!
