### ISSUE TITLE
Enforcing URI encode seems to break

### ISSUE THREAD

**Issue by stephanebachelier** [tomas/needle#184]
Since the move to [encode URI](https://github.com/tomas/needle/commit/f62e0958b8d24f6231f7611e043a08a0deddd7e7) some issues start to appears.

Rather than always encoding URI it should either be opt-in using an option or done by the one using needle.

Maybe something like : 

```
needle
  .post('https://my.server.com/foo', data, { encode: true })
  .on('end', function() {
    console.log('Ready-o, friend-o.');
  })
```

See 
* #183 
* https://github.com/alexanderGugel/ied/issues/164 fixed in https://github.com/alexanderGugel/ied/pull/165 by downgrading to needle @1.0.0. There are more details in the commit message

**Comment by kfitzgerald** [comment]
Agreed. #171 should be totally rolled back immediately, as it breaks properly encoded urls by double encoding them. 

If the developer is trying to fetch a broken URL, that's their problem, not needle's.
