### ISSUE TITLE
Socket error: { "message": "socket hang up" "code": "ECONNRESET"}

### ISSUE THREAD

**Issue by yangguoyk2015** [tomas/needle#188]
I am facing issue { "message": "socket hang up" "code": "ECONNRESET"},  when using Needle (v1.0.0) as client request to call a https server. After several days researching, it located at the needle.js file, 
line 600 ~ 622, where it setup the open_timeout at line 600, and end the request at line 618.  Normally, if the remote server can connect in short time, the open_timeout timer will be clear at line 416, but in case the open_timeout is set very short (I set 10 ms for my case), or remote server is slow and take longer time to  execute the connection, because, we already call request.end() at Line 618, then trying to call request.abort() at line 416, where we will got the  { "message": "socket hang up" "code": "ECONNRESET"}. 

here is my JSON response:
`{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "socket hang up",
    "code": "ECONNRESET",
    "stack": "Error: socket hang up\n    at createHangUpError (_http_client.js:211:15)\n    at TLSSocket.socketCloseListener (_http_client.js:243:23)\n    at emitOne (events.js:82:20)\n    at TLSSocket.emit (events.js:169:7)\n    at TCP._onclose (net.js:486:12)"
  }
}`

I hope somebody can help to review this issue, as this issue cause an continuous memory consumption in my case, where its keeping creating an object called "TLSscoket" for each call and never release them, even force node GC.

**Comment by tomas** [comment]
Hi @yangguoyk2015, 

Does it also happen on older versions? Say, 0.8 or 0.9?

**Comment by yangguoyk2015** [comment]
@tomas , i repeated same error even by v0.8.0, v0.9.0. As i can see they are using the same way to abort request. And going deeper, i found the issue is thrown out from had_error function in needle.js.
`  function had_error(err) {
    debug('Request error', err);
    done(err || new Error('Unknown error when making request.'));
  }`

**Comment by GitTristan** [comment]
I am facing the same issue (v1.1.2).  

```error: err in needle call  Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Socket.require.EventEmitter.emit (/Applications/WebStorm.app/Contents/plugins/spy-js/server/lib/tracerNode.js:8:4054)
    at TCP._handle.close [as _onclose] (net.js:492:12)```

and then,
```COOKIE_PAIR is not defined
ReferenceError: COOKIE_PAIR is not defined
    at parseSetCookieString (/node_modules/needle/lib/cookies.js:56:42)
    at /node_modules/needle/lib/cookies.js:32:49
    at Array.reduce (native)
    at Object.parseSetCookieHeader [as read] (/node_modules/needle/lib/cookies.js:29:71)
    at ClientRequest.<anonymous> (/node_modules/needle/lib/needle.js:505:63)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at ClientRequest.require.EventEmitter.emit (/Applications/WebStorm.app/Contents/plugins/spy-js/server/lib/tracerNode.js:8:4054)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.require.EventEmitter.emit (/Applications/WebStorm.app/Contents/plugins/spy-js/server/lib/tracerNode.js:8:4054)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

**Comment by tomas** [comment]
Ok I will take a look at this when I have a minute! Thanks for reporting.

**Comment by yangguoyk2015** [comment]
@tomas, just for your reference, 

- 1. seems the socket hangup error is released since node v0.8.20 (my node version is v4.4.7) https://github.com/ether/etherpad-lite/issues/1541
- 2. this is the exactly same scenario of our issue. http.IncomingMessage omits events when aborted on client side (https://github.com/nodejs/node/issues/7732), http://www.clock.co.uk/blog/preventing-http-raise-hangup-error-on-destroyed-socket-write-from-crashing-your-nodejs-server, the difference is that my client is node http.clientRequest, the target server is non-node, but a C++ product
- 3. from my heap dump, i see there is reference to the needle, attach a screenshot for your reference. 

![image](https://cloud.githubusercontent.com/assets/12314244/18653561/3e750082-7f0d-11e6-8fe9-471183017e27.png)

**Comment by maccman** [comment]
We are seeing the same issue too.

**Comment by tomas** [comment]
Ok, looking at this right now.

**Comment by tomas** [comment]
@yangguoyk2015 The issue you linked to refers to something different, which is Node's `http.IncomingMessage` (server side) not triggering events when the client aborts a request. In your case Needle is aborting the request because you're specifiying a open_timeout which triggers -- that's what causes the ECONNRESET error to be thrown. What are you expecting to happen instead?

@GitTristan Can you please explain better what's your scenario? Are you also setting a low open_timeout via Needle options? What are you expecting to happen when the timeout actually triggers. The second error you posted is something different, by the way. Are you wrapping Needle using Webpack or using a transpiler? Something weird is happening with the [COOKIE_PAIR constant](https://github.com/tomas/needle/blob/master/lib/cookies.js#L10).

**Comment by tomas** [comment]
Ping @yangguoyk2015 and @GitTristan

**Comment by tomas** [comment]
@maccman Any additional pointers? I'd love to help figuring this one out but I'm kind of stuck.

**Comment by jianzhou520** [comment]
Have any progress?

**Comment by tomas** [comment]
@jianzhou520 to be honest this doesn't seem to be an error on Needle's side. You simply get this error because the either the open or read timeouts are being triggered, as discussed on issue #192. So I suggest increasing the `open_timeout` or `read_timeout` settings in your code and seeing what happens.

Otherwise please open a new issue with a full example of your case so I can actually replicate the error and find out if there's something wrong. :)

**Comment by MetaMmodern** [comment]
Hey, I've got the same error( But only in deployment in docker container using Cloud Run by Google. When using Heroku hosting I did not have such problem. Also, timeout did  not help, because my server is just waiting for something and....gives me that error.
