### ISSUE TITLE
Would you be interested in W3C Headers?

### ISSUE THREAD

**Issue by jimmywarting** [tomas/needle#190]
Maybe include W3C [Headers](https://www.npmjs.com/package/fetch-headers) into this api? Or at least support it if someone were to do include it

This could be used for both request and response headers and it has a good way of looping over all of them with both es5 syntax forEach and for...of among other things

**Comment by tomas** [comment]
Hi, and sorry for not responding earlier. Can you elaborate more on this? What would we gain by including this package into Needle?

**Comment by tomas** [comment]
Ping @jimmywarting
