### ISSUE TITLE
Socket hang up error on high concurrency 

### ISSUE THREAD

**Issue by dodtsair** [tomas/needle#192]
Hello,  

I thought this might be related to #188, but I decided to open it as a different issue just in case.

needle works fine, when I keep the request rate low.  But when the request rate kicks over a certain threshold I start getting constant stream of socket hang up errors.  I have sample code that demonstrates it.

```
var Q = require('q');
var needle = require('needle');
var request = require('request');
var logger = require('log4js').getLogger("deleteme");

var batches = 2;
var batchSize = 200;

var express = require('express');
var app = express();

app.get('/', function(req, res){
  res.send('hello world');
});

var server = app.listen(8001);


var requestBatches = [];
for(var batchIndex = 0; batchIndex < batches; ++batchIndex) {
  const thisBatch = batchIndex;
  requestBatches.push(Q.delay(batchIndex * 1000 + 1).then(function() {
    var requests = [];
    var needles = [];
    var needleErrors = 0;
    var requestErrors = 0;
    for( var queryIndex = 0; queryIndex < batchSize; ++queryIndex) {
      requests.push( Q.nfcall(request, "http://localhost:8001/").catch(function(error) {
        logger.error("Error: ", error.message);
        ++requestErrors;
        throw error;
      }));
      needles.push( Q.nfcall(needle.get, "http://localhost:8001/").catch(function(error) {
        logger.error("Error: ", error.message);
        ++needleErrors;
        throw error;
      }))

    }
    return Q.allSettled(requests.concat(needles)).then(function() {
      if(needleErrors) {
        logger.error("Needle Batch: ", thisBatch, " failed ", needleErrors, "/", batchSize)
      } else {
        logger.info("Needle Batch: ", thisBatch, " all success")
      }
      if(requestErrors) {
        logger.error("Request Batch: ", thisBatch, " failed ", needleErrors, "/", batchSize)
      } else {
        logger.info("Request Batch: ", thisBatch, " all success")
      }
    })


  }));


}


Q.allSettled(requestBatches).finally(function() {
  logger.info("all done");
  server.close();
});


```
 
When you run this script you'll get output like

```
[2016-11-15 12:48:35.869] [ERROR] deleteme - Error:  socket hang up
[2016-11-15 12:48:35.874] [ERROR] deleteme - Error:  socket hang up
[2016-11-15 12:48:35.877] [ERROR] deleteme - Error:  socket hang up
[2016-11-15 12:48:35.881] [ERROR] deleteme - Error:  socket hang up
[2016-11-15 12:48:35.886] [ERROR] deleteme - Error:  socket hang up
[2016-11-15 12:48:36.010] [ERROR] deleteme - Needle Batch:  0  failed  68 / 200
[2016-11-15 12:48:36.049] [INFO] deleteme - Request Batch:  0  all success
[2016-11-15 12:48:42.733] [ERROR] deleteme - Needle Batch:  1  failed  199 / 200
[2016-11-15 12:48:42.736] [INFO] deleteme - Request Batch:  1  all success
[2016-11-15 12:48:42.748] [INFO] deleteme - all done
```

I am currently using node v6.9.1 expressjs 4.13.4 needle 1.3.0 and for comparison request 2.78.0, Ubuntu 14.04.

**Comment by tomas** [comment]
Interesting! Let me take a deeper look and I'll get back to you.

**Comment by tomas** [comment]
I just tested your code on Node v4.4.7 with express 4.14.0 and needle 1.3.0 and got no errors:

``` sh
$ node concurrency.js 
[2016-11-15 13:06:12.808] [INFO] deleteme - Needle Batch:  0  all success
[2016-11-15 13:06:12.811] [INFO] deleteme - Request Batch:  0  all success
[2016-11-15 13:06:13.741] [INFO] deleteme - Needle Batch:  0  all success
[2016-11-15 13:06:13.741] [INFO] deleteme - Request Batch:  0  all success
[2016-11-15 13:06:13.742] [INFO] deleteme - all done
```

I'll see what happens with a newer version of node.

**Comment by tomas** [comment]
And Node v7.1.0 also gives no errors:

```
[2016-11-15 13:09:56.473] [INFO] deleteme - Needle Batch:  1  all success
[2016-11-15 13:09:56.476] [INFO] deleteme - Request Batch:  1  all success
[2016-11-15 13:09:57.356] [INFO] deleteme - Needle Batch:  0  all success
[2016-11-15 13:09:57.357] [INFO] deleteme - Request Batch:  0  all success
[2016-11-15 13:09:57.357] [INFO] deleteme - all done
```

**Comment by tomas** [comment]
Ok if I increase the `batchSize` number in your code I start seeing those "socket hang up" errors.

**Comment by tomas** [comment]
Ok there's nothing wrong, really. Those socket hang up errors are simply the result of the default `open_timeout` setting that Needle has. It simply means that the client is not able to connect to the server within a 10-second window, and thus Needle is aborting those requests.

You can increase or turn off the open timeout using the `open_timeout` option when calling `needle.get`, or overwrite the default by calling `needle.defaults({ open_timeout: 60000 })`.

Hope this helps.

**Comment by dodtsair** [comment]
@tomas I assume then request does a similar thing but with a higher open_timeout. 

When I am doing my tests I am doing 2 batches of 200 spaced by 1 second.  So that means that the express server is unable to open the connection for those 200 connections in the span of 10 seconds. 

I am just rewording and confirming what you are saying.  

Since I am hitting the express server all at once with 200 connections, the timer begins for each connection almost at the same time.  The server responds to each connection one at a time, so if it takes more than 100ms to answer the connection then the last connections get timeout errors.

**Comment by tomas** [comment]
Yes. This also explains why in my case I had to increase the limit to start getting the errors -- it depends on whether the Express app is able to process the requests on time or not.

I'm closing this issue then, but feel free to open a new one if you find something else.
