### ISSUE TITLE
Output file size not correct straight after callback

### ISSUE THREAD

**Issue by alirussell** [tomas/needle#193]
This is a hard one to reproduce and/or explain but will give it a go.

The file size of `output` files returned using `fs.statSync(file).size` is not correct directly after the callback is returned.

I have the following code which is used in my app, where afterSuccess is the callback from needle:

```
  afterSuccess: function (body, input) {
    return when.promise(function (resolve, reject) {

    	console.log('FILE SIZE BEFORE', fs.statSync(input.temp_file_name).size);

    	setTimeout(function() {
	    	console.log('FILE SIZE AFTER', fs.statSync(input.temp_file_name).size);
    	}, 2000);
		
    });
  }
```

It gets the size of the file written to `output` and then it waits 2 seconds and gets it again

(It may look strange but its part an internal framework we are building, the afterSuccess is called when the response from needle is 200, so body will be the body response from needle, input just happens to have the temp file name which is used as `output`)

The issue I'm getting, is that when running this code on AWS lambda (its ok locally), I'm getting the following log lines:

```
FILE SIZE BEFORE 67822
FILE SIZE AFTER 84445
```

So you can see that the initial callback file size is not correct, but after 2 seconds its ok.

Taking a look at the code, i noticed that the file is written to disk chunk by chunk and when its finished there is no callback:

https://github.com/tomas/needle/blob/master/lib/needle.js#L531
```
      out.on('end', function() {
        if (file.writable) file.end();
      });
```

Im wondering if the disks used in Lambda are perhaps particularly slow and that the general needle callback is done before the writing to disk has finished?

Could we delay the callback until the file has been written to disk (on most systems this should be immediately).

**Comment by tomas** [comment]
Good one @alirussell, thanks for reporting.

What would you expect to happen within the `end` callback you mentioned, then?

**Comment by alirussell** [comment]
Ive actually just realised that we don't have the very latest version of needle and that this https://github.com/tomas/needle/commit/d31ff62549162791da2308023c46e5a5ec764d92 commit maybe a part of the solution

Will test it quickly

**Comment by tomas** [comment]
Sure, no prob. Let me know how it goes.

**Comment by alirussell** [comment]
Yep, it is still an issue if i add the file.end part.  It seems that the file is written to and file.end is called before the main callback as you would expect:

```
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.WRITE
NEEDLE FILE.END
NEEDLE CALLBACK
FILE SIZE BEFORE 73646
FILE SIZE AFTER 84445
```

I suppose you would expect the main callback to only be fired when the file has been fully written to disk?

could you have some sort of semaphore/lock on the callback until the file is completely finished writing to disk, perhaps using `file.on('close')`?

**Comment by tomas** [comment]
Ok, let me take a look and I'll get back to you.

**Comment by tomas** [comment]
Ok I think I have it.

**Comment by tomas** [comment]
Ok just pushed a fix for this. Can you try it out and see if it works?

**Comment by alirussell** [comment]
ah, great. thanks!!

Will give it a test tomorrow morning!

**Comment by alirussell** [comment]
All looks good, thanks @tomas 👍 

``
FILE SIZE BEFORE 84445
FILE SIZE AFTER 84445
```

Any idea when you maybe able to get this released?

**Comment by tomas** [comment]
A few minutes ago, actually. :)

`npm update needle` !
