### ISSUE TITLE
browserify error

### ISSUE THREAD

**Issue by mmclau14** [tomas/needle#195]
first of all, i really like this package, so thank you for that.
i tried browserifying this package and found that xml2js was missing from the build.
looks like it's being used on line 54 in parsers.
was able to get around it for now by installing xml2js, but i would think that devDependencies are for the needle team, not for everyone else to have to use and that xml2js should really be in the dependencies if it is going to be supported.

**Comment by tomas** [comment]
Hi, 

xml2js is not a devDependency, it's an optional runtime dependency, as stated in the readme. We don't enforce its use precisely to prevent users from installing stuff they might not need. I guess we could add a section in the readme regarding webpack and browserify though. :)

**Comment by mmclau14** [comment]
cool. that sounds like a good solution to me
