### ISSUE TITLE
Does needle support an OAuth Authorization Header?

### ISSUE THREAD

**Issue by leonardorb** [tomas/needle#199]
Basically, what I'm trying to do is:
```
const options = { headers: { Authorization: 'OAuth <token>' } };
```
then:
```
needle.request('get', url, options);
needle.on('data', () => {
  // work with the data here, probably write somewhere
});
needle.on('end', () => {
  // end the write stream
});
```

Maybe I'm missing something, but I'm getting `401`s doing like above.

**Comment by leonardorb** [comment]
Hmm. Taking a look at https://github.com/tomas/needle/blob/master/lib/auth.js I think I found my answer. Any plans to support other types of authentication? I can help :)

**Comment by tomas** [comment]
Sure, what other types?

The options hash in your example seems to be ok, but the observable is not needle itself but the object returned when calling `request`, e.g.:

    needle
      .request('get', url, options)
      .on('data', () => {
        // work with the data here, probably write somewhere
      })
      .on('end', () => {
        // end the write stream
      });

**Comment by tomas** [comment]
Closing this one for the time being. Feel free to reopen when/if you have more info.

**Comment by sparshturkane** [comment]
You can use this example code to pass headers in needle

```
var url = "https://example.com";
var params = {
"name" : "john",
"email" : "test@test.com"
}

var header = {
       headers: {
            'Authorization': "Bearer Token"
        }
}
needle.request('get', url, params, header, function (err, resp) {
        console.log(resp);
        res.send(resp.body)
});
```
