### ISSUE TITLE
Problem fetching the URL https://docs.npmjs.com/getting-started/what-is-npm

### ISSUE THREAD

**Issue by giltayar** [tomas/needle#202]
I tried to use `needle.head('https://docs.npmjs.com/getting-started/what-is-npm', ...)` and got an error:

```
Error: unexpected end of file
      at Zlib._handle.onerror (zlib.js:355:17)
```

curl --head https://docs.npmjs.com/getting-started/what-is-npm works fine.

(I didn't try needle.get on this url)

**Comment by tomas** [comment]
Both `.get` and `.head` work OK for me, after doing a quick test under node v4.7.2.

What version of node (and needle) are you running?

**Comment by giltayar** [comment]
You're right.

It doesn't happen in v4.7.2 (or 4.7.3, which is the latest v4).

But it _does_ happen in v5.12.0 (which is the latest v5), v6.9.5 (latest v6), and v7.5.0 (latest v7).

This is the code I tried:
```
const needle = require('needle')

needle.head('https://docs.npmjs.com/getting-started/what-is-npm', (err, res) => {
  if (err)
    return console.error(err)

  console.log(res)
})
```

And this is the output of my `npm ls` (of the module with the just the above code):
```
└─┬ needle@1.4.3
  ├─┬ debug@2.6.0
  │ └── ms@0.7.2
  └── iconv-lite@0.4.15
```

**Comment by tomas** [comment]
I was finally able to reproduce the error. I'll take a deeper look now and let you know what I find. Thanks for reporting!

**Comment by tomas** [comment]
Ok, found out what's going on. [This change](https://github.com/nodejs/node/pull/2595/files) in Node made gunzip more rigid when dealing with truncated inputs. It's a pretty easy fix, though. I'll push a new version in a minute.
