### ISSUE TITLE
http/s Agent

### ISSUE THREAD

**Issue by voidmonk** [tomas/needle#213]
Hi, quick question: if a http agent is passed, but the request redirects to a https URL, then is a new https agent created for it (because http agent won't work for https URL, and vice versa)?

**Comment by tomas** [comment]
No, if needle redirects to a new URL it will keep using the same agent you passed originally. Did you get a different behaviour?

**Comment by voidmonk** [comment]
Ok, but I suppose the `http` agent will throw an exception if redirecting to a https URL?

Some libraries handle this situation by requiring both `http` and `https` agents to be specified, and then using either based on the URL scheme.

**Comment by tomas** [comment]
Hi @voidmonk, were you able to try this out? Did it work as expected?

**Comment by voidmonk** [comment]
Ended up using native http/s instead of needle, so didn't try it out.
