### ISSUE TITLE
Adding an authorization header with a bearer token

### ISSUE THREAD

**Issue by mm-wang** [tomas/needle#214]
I have a route that is requesting an `authorization: Bearer [token string]` in the header. I've included it in options the following ways:

```
var options = {
   json: true,
   headers: {
      authorization: "Bearer (token string)"
   }
};
```

and 

```
var options = {
   json: true,
   authorization: "Bearer (token string)"
};
```

In both cases, it seems that the request string is actually adjusted. The form for the requests is: 
```
(REQUEST METHOD) /api/(endpoint)?json=true&[authorization]=Bearer%20(token string) HTTP/1.1
```
for the first option, and authorization is removed from brackets in the second. Is there a way to send a request through needle that will recognize this authorization header and add the token string after Bearer without appending a query string to the endpoint?

**Comment by tomas** [comment]
Looks like you're passing the options in the position that Needle is expecting the `data` argument:

``` js
needle.post(url, data, options)

// instead of

needle.post(url, options)
```

If you don't expect to send data, just pass `null`.

**Comment by mm-wang** [comment]
Ah, of course. Thanks!
