### ISSUE TITLE
inconsistency file downloading

### ISSUE THREAD

**Issue by vbahtev** [tomas/needle#215]
Every time when try to download file i get file with non actual file size. Some time i get file size bigger than actual, sometimes smaller. 

Version that i used is 1.6.0

Here is code:

``` javascript
let needle = require('needle');
let fs = require('fs');
let writeStream = fs.createWriteStream('file');

needle.get('http://ec.europa.eu/external_relations/cfsp/sanctions/list/version4/global/global.xml').pipe(writeStream).on('close', function() {
    console.log('finish');
});
```

**Comment by tomas** [comment]
Try using the 'done' event. And sorry for the late response!

**Comment by vbahtev** [comment]
'done' event is not help.
Please try example and run it to view inconsistency.
After every run just check file size 
If you need from more information let me know
