### ISSUE TITLE
Is it possible to send multi files at one POST?

### ISSUE THREAD

**Issue by zenchanhk** [tomas/needle#216]
I am wondering that it is possible to send multi files at one POST, I didn't find a way to send more than one files at one time. Thanks.

**Comment by tomas** [comment]
Hi @zenchanhk, of course you can: 

```
var data = {
  upload1: { 
    file: 'linux.png', 
    content_type: 'image/png' 
  },
  upload2: { 
    buffer : fs.readFileSync('./package.zip'), 
    filename : 'mypackage.zip',
    content_type : 'application/octet-stream'
  }
}

needle.post('some.server.com', data, { multipart: true })
```

Let me know if that works for you.

**Comment by zenchanhk** [comment]
@tomas Hi Tomas, thanks for your quick reply. It seems not working well with nodejs +  Express + multer. Here is code on my server side:
`router.post('/api/upload', upload.array('images', 20), actions.upload);`
Is it possible to use something like this:
```
var data = {
  images: [{ 
    file: 'linux.png', 
    content_type: 'image/png' 
  }, {     
    file: 'mypackage.zip',
    content_type : 'application/octet-stream'
  }]
}
```

needle.post('some.server.com', data, { multipart: true })

**Comment by tomas** [comment]
@zenchanhk of course it is. Try creating an endpoint at https://hookbin.com and running your example code. You should get the two files.

**Comment by zotakk4o** [comment]
Hi Team, there seems to be a problem sending multiple files at the same field(part) name. 

```
var data = {
  images: [{ 
    file: 'linux.png', 
    content_type: 'image/png' 
  }, {     
    file: 'linux(1).png', 
    content_type: 'image/png' 
  }]
}
```
Request with this data will be sent as:
```
{
    images[0]: ...,
    images[1]: ...
}
``` 
Can you please check it?
