### ISSUE TITLE
‘follow_set_cookies’  just drop all cookies not listed in ‘set-cookies’ is it right？ or a bug？

### ISSUE THREAD

**Issue by ash0080** [tomas/needle#223]
```
needle('get', 'whateverdomain', {
  headers: {
    cookies: {
      i_wanna: 'see tomorrow'
    }
  }
}).then(resp => {
  if (!resp.cookies.i_wanna) 
    console.log('but simply be killed :(')
})
```

**Comment by ash0080** [comment]
My headache is, after visiting the second page, in my browser, JSESSIONID still exist.  but in needle seems the result is different.
as I know, If the server side need to kill a recode, it will send a 'set-cookie' and a expiration time,
but as displayed in the shots, I can't find one

![2017-11-01_01-06-06](https://user-images.githubusercontent.com/2803210/32237818-f01628ba-bea0-11e7-832a-e687e765cc1f.png)

**Comment by tomas** [comment]
Can you provide an example snippet and a description of the expected outcome so I can reproduce the error. I'm not sure I understand what the problem is. What does needle have to do with your browser, by the way?

**Comment by ash0080** [comment]
Actually I find that all request cookies will be dropped in Promise.then() style, only 'set-cookies' in response will be pass to the next .then(), strange?
