### ISSUE TITLE
If url contains '@', request ignores username and password

### ISSUE THREAD

**Issue by wip0** [tomas/needle#224]
<code>
let username = 'abc';
let password = 'def';
let url = 'http://www.xxx.com/abc/@def/xyz.zip';
needle.put(targetUrl, stream, { username: username, password: password, parse: true });
</code>

In needle.js
<code>
  if (uri.indexOf('@') !== -1) { // url contains user:pass@host, so parse it.
    var parts = (url.parse(uri).auth || '').split(':');
    options.username = parts[0];
    options.password = parts[1];
  }
</code>

'@' in the above url is not in the 'user:pass@host' format. But it is a part of url.

**Comment by tomas** [comment]
Ahh, I see. Now #255 makes sense. I'll take a second look at it now.
