### ISSUE TITLE
Problem with promise needle version when export it to other source file

### ISSUE THREAD

**Issue by Fly-Style** [tomas/needle#228]
Hello!
I have Node 8.9 and `needle` version 2.0.1 : 
```"dependencies": { ...  "needle": "^2.0.1" ... }```

I need to work with `Promise` version of needle API, but seems it doesn't work. 
I add `needle` as the module and trying to launch as function (I saw the docs), but have troubles : 
```
const needle = require('needle');

// ... 
module.exports = {
  getStats(url) {
      needle('get', url).then((res) => {
        console.log(res.body);
      }
  },
//... 
}
```
and I got this when I call `getStats` to other source file (which has also imported needle) : 

```
needle('get', url).then((res) => {
      ^
SyntaxError: Unexpected token (
```
  
Maybe I did something wrong, I'm pretty newbie in ES6 standart and Node as well.  Maybe I failed when make import or something like that.
Thanks for attention!
Cheers, Alexander.

**Comment by tomas** [comment]
Are you sure you have native support for ES6 syntax? Try with the regular syntax and see if it helps:

```
module.exports = {
  getStats: function(url) {
      needle('get', url).then(function(res) {
        console.log(res.body);
      })
  }
}
```

**Comment by Fly-Style** [comment]
Your code works fine, thank you! 
Maybe it was my mistake or some Node`s fail.
