### ISSUE TITLE
Event "err" and event naming conventions

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [tomas/needle#230]
Why has the error event a truncated name? All the other events have a "proper" name, e.g.
- timeout
- response
- redirect
- header
- done

But the event name for error is "err" which seems like an unnecessary special case to me. 

I know that in some languages "error" is a reserved keyword so that "err" is used instead. But that is not the case here, right?

**Comment by tomas** [comment]
It's not a reserved keyword, but it Nodeland it tends to be reserved for internal events -- you get 'unhandled "error" event' if you don't set up a listener. I guess there's no harm really in renaming the event, as there are no collisions of any kind, which I tried to avoid altogether when implementing it.
