### ISSUE TITLE
Options being ignored

### ISSUE THREAD

**Issue by doowb** [tomas/needle#233]
When using the following form for a `get` request, the `options` are being ignored and being used as `data`:

```js
needle('get', 'http://example.com', {json: false})
  .then((res) => console.log(res.raw))
  .catch((err) => console.error(err));
```

I think the argument handling [here](https://github.com/tomas/needle/blob/24b3e1840efc105981928ca83047d7bbfcd312ad/lib/needle.js#L730-L748) is causing the issue, but I'm not sure if there are other places that would need to be updated.

If this isn't intentional, I'll try to submit a PR when I have a chance.

**Comment by tomas** [comment]
Fixed! Thanks for the heads up.
