### ISSUE TITLE
Multipart fields with brackets in names

### ISSUE THREAD

**Issue by SergeyYermak** [tomas/needle#235]
Trying to simulate browser file upload request, it is sending multipart fields like that:
```
------WebKitFormBoundaryVUPdjEIH1BKgPvL1
Content-Disposition: form-data; name="category[]"

1
------WebKitFormBoundaryVUPdjEIH1BKgPvL1
Content-Disposition: form-data; name="category[]"

4
```
In needle file options I'm declaring category field:
```
let file = {
  ...
  category: ['1'],
  ...
}
```
And when I'm inspecting in debugger, it shows that request was sent like that:
```
----------------------NODENEEDLEHTTPCLIENT
Content-Disposition: form-data; name="category[0]"

1
```
Is this intentional (I mean index number in brackets)?
Because I have response from server to select a category after this request.

**Comment by tomas** [comment]
Yes this is intentional, but the behavior on the server side shouldn't differ. Are you not getting an array at `params.category`? What type of server are you running?

**Comment by SergeyYermak** [comment]
Unfortunately server is not mine, I'm just automating some browser task, for this part I did not tested much and switched to request module.

**Comment by tomas** [comment]
Sure, no problem. I just don't see where/what the problem is, since the end result from the server side should be the same.
