### ISSUE TITLE
The use of fs

### ISSUE THREAD

**Issue by greaka** [tomas/needle#237]
I have a problem that this package wants to use fs.
fs is currently not in use and not installable from npm (see https://www.npmjs.com/package/fs)
I get the following error message:

> This dependency was not found:
> 
> * fs in ./node_modules/needle/lib/needle.js, ./node_modules/needle/lib/multipart.js

both files use `var fs = require('fs')`
How should I deal with this problem?

**Comment by rchipka** [comment]
The `fs` package is included in the nodejs standard library

https://nodejs.org/api/fs.html

**Comment by tomas** [comment]
@Greaka Are you trying to bundle `needle` with something like webpack or browserify?

**Comment by Greaka** [comment]
I am trying to bundle it with webpack, yes.
