### ISSUE TITLE
How to set a customed headers?

### ISSUE THREAD

**Issue by phper-chen** [tomas/needle#242]
For example, i have done these:
```
return await new Promise(function(resolve, reject) {
        needle.post('localhost:7001/test/remote', streamBuffer,
          {
            headers: {
              'X-ACCESS-ID': APP_ID,
              'X-ACCESS-NONCE': nonce,
              'X-ACCESS-SIGNATURE': signature,
            },
            multipart: true,
          },function(err, res) {
            if (err) reject(err);
            resolve(res.body);
          });
      });
```
what headers i get from reciever with 'multiparty' in console is:
```
{
 'content-disposition': 'form-data; name="Redis"; filename="Redis"',
  'content-transfer-encoding': 'binary',
  'content-type': 'multipart/form-data'
 }
```
there was no customed headers,plz giving me a guidence...

**Comment by tomas** [comment]
That's weird. Looks like something is messing up your headers, because 'Content-Disposition' should be part of the request's _body_, not the headers. What does `streamBuffer` look like?

**Comment by phper-chen** [comment]
It is my fault, i should print the headers of req rather than print the the stream headers of 'PassThrough' after using the 'multipart'.
Thank u~
