### ISSUE TITLE
Get access to header before streaming

### ISSUE THREAD

**Issue by Borewit** [tomas/needle#265]
Hi @tomas,

I tried to read an audio file using needle, and I would like to stream it.
Is there a way to get access to the headers, before the actual content is read?

For the audio file it is important I get access to the `Content-Type` & `Content-Length` first, because I need to select the appropriate parser.

Related discussion on [stackoverflow](https://stackoverflow.com/questions/31649901/how-to-get-response-headers-when-using-needle-js-in-streaming-mode), but it did not bring me any closer to a solution.

**Comment by tomas** [comment]
Hi @Borewit. Doesn't the `headers` event help you solve your problem?

**Comment by Borewit** [comment]
Thank @tomas, that worked out just fine!

```JavaScript
return new Promise<IHttpResonse>((resolve, reject) => {
  const stream = needle.get(url);
  stream.on('headers', headers => {
    resolve({stream, headers});
  });
  stream.on('err', err => {
    reject(err);
  });
});
```
