### ISSUE TITLE
ssl.key ssl.cert in test/keys/

### ISSUE THREAD

**Issue by markwolff** [tomas/needle#277]
Hey, I am seeing `ssl.key` and `ssl.cert` in my node_modules folder when I add needle to my repo. Where are these generated? I see they are different on different machines, so I'm assuming they are my keys.

#### Repro
```
npm i needle
ls node_modules/needle/test/keys
```

**Comment by tomas** [comment]
That's weird. Looks like the keys used for testing got included in the published package. Lemme check.

**Comment by tomas** [comment]
Yup, confirmed. Just pushed a new version without them. Thanks for reporting!
