### ISSUE TITLE
Error in node 4.x due to debug dependency

### ISSUE THREAD

**Issue by gpcastro** [tomas/needle#278]
PM2 is failing in Node 4.x versions since the dependency on `debug` has been bumped to `^4.1.0` (through 78309e5543f9491e25198300a053ceae772b41a2). This is the error:

```
/usr/local/lib/node_modules/pm2/node_modules/needle/node_modules/debug/src/node.js:132
        let val = process.env[key];
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Debug [dropped](https://github.com/visionmedia/debug/issues/611)  support for node 4.x, so either the dependency on debug has to be downgraded, or engines field on `package.json` has to be updated.

**Comment by tomas** [comment]
Good point. What do you suggest?

**Comment by gpcastro** [comment]
I'd suggest downgrading the version of `debug` to maintain backward compatibility with Node 4.x. 

If that version change is really necessary, a major version update of `needle` is needed instead since it is not backward compatible.

**Comment by tomas** [comment]
OK. So what was the last version of debug that supported Node 4.x?

**Comment by gpcastro** [comment]
I've tried with 3.2.6 (their latest before 4) and it worked fine. 

The release description says "This backport fixes a 4x performance regression when debug is disabled." so it should be good.

**Comment by tomas** [comment]
Ok, just pushed a new version (needle@2.4.0) with debug@3.2.6.

Thanks!
