### ISSUE TITLE
Feature: support Brotli (br) compression

### ISSUE THREAD

**Issue by colinskow** [tomas/needle#281]
When a web server sends a page with Content-Encdoding: "br" (Brotli compression), Needle spits out a body of gibberish rather than properly decompressing it. NodeJS LTS supports Brotli, so it should be a no-brainer to implement.

**Comment by tomas** [comment]
Sure, sounds great. Would you like to give it a shot?

**Comment by colinskow** [comment]
Alright, I just took a look and it's real easy. I just need to add 'br' to the list of decompressors. I'll give it a shot over the next few days.
