### ISSUE TITLE
repeats twice for some reason

### ISSUE THREAD

**Issue by redimongo** [tomas/needle#294]
So I am trying to do something simple which is use needle.get to fetch a pre-roll station ID before it plays the podcast.

It works fine. However here is the issue. according to the logs it is running the code twice.
I am wondering what am I doing wrong as I would like to be able to use the .on('end') to store a database endtime - but i don't need to it run twice.

```
STATION_ID Completed
754542
STATION_ID Stream END
get POdcast ran
get data connected!
63062853
STATION_ID Completed
754542
STATION_ID Stream END
get POdcast ran
get data connected!
63062853
```

````
router.get('/track/:url(*)', (req, res) =>{
    var url = req.params.url.substr(0); 
    var length = 0;
    var clients = [];
    var e = 0;
    /* AD SYS */
    var remote = "https://storage.googleapis.com/ad-system/testfolder/OUTOFAREA.mp3";  
    var adsys = needle.get(remote)
    /* PODCAST */
    var filesize = needle.get(url, function(error, response, body) {
       if(error){
        e = 505;
        res.send("<html><head></head><body>NOPE</body></html>");
        console.log(error)
        //filesize.end();
        res.end();
        
       }
    });

   
        adsys.on('response', function(res) {
            console.error("STATION_ID Completed");
            length =  Number(res.headers['content-length']);
            console.log(length);           
        });

        filesize.on('response', function(res) {
                console.error("get data connected!");
                console.log(res.headers['content-length']);
                a = Number(res.headers['content-length']);
                length = length+a;
                
      });
      res.set({
        "Content-Type": "audio/mpeg",
        'Transfer-Encoding': 'chunk',
    //    'Content-Disposition': 'attachment',
    //    'Content-Length':length
    });

      adsys.on("end", function() {
        
        console.error("STATION_ID Stream END");
       
        getPodcast();
     
        
        //res.end();
    });  


    adsys.on("data", function (chunk) {
            // console.log(clients.length);
            if (clients.length > 0){
                for (client in clients){
                    clients[client].write(chunk);
                    //console.log(chunk);
                };
            }
        
    });

    function getPodcast(){
        console.log("get POdcast ran");
        filesize.on("data", function (chunk) {
            // console.log(clients.length);
            if (clients.length > 0){
                for (client in clients){
                    clients[client].write(chunk);
                    //console.log(chunk);
                };
            }
            
        });
    }
    clients.push(res);
});`
```

**Comment by tomas** [comment]
Try changing `adsys.on('end', fn)` to `adsys.on('done', fn)`

**Comment by redimongo** [comment]
> Try changing `adsys.on('end', fn)` to `adsys.on('done', fn)`

I tried this and it still ran twice.
`STATION_ID Completed
 X STATION_ID Stream END
get POdcast ran
get data connected!
63062853
STATION_ID Completed
 X STATION_ID Stream END
get POdcast ran
get data connected!`

**Comment by tomas** [comment]
I'm not sure what you're trying to do, but I just ran your code (removing the `res` calls) and it ran only once:

```
STATION_ID Completed
754542
get data connected!
undefined
STATION_ID Stream END
get POdcast ran
```

Are you sure the request isn't being triggered twice? Try logging whenever the `'/track/:url(*)` route gets called.

**Comment by redimongo** [comment]
> I'm not sure what you're trying to do, but I just ran your code (removing the `res` calls) and it ran only once:
> 
> ```
> STATION_ID Completed
> 754542
> get data connected!
> undefined
> STATION_ID Stream END
> get POdcast ran
> ```
> 
> Are you sure the request isn't being triggered twice? Try logging whenever the `'/track/:url(*)` route gets called.

So the URL looks like.
https://api.drn1.com.au:9000/podcast/track/https://storage.googleapis.com/radiomediapodcast/wellwellnow/season1/S01E04.mp3

Do I need the res stuff for this to work?

If you could post the changes you made that would be great. :)

**Comment by redimongo** [comment]
> I'm not sure what you're trying to do, but I just ran your code (removing the `res` calls) and it ran only once:
> 
> ```
> STATION_ID Completed
> 754542
> get data connected!
> undefined
> STATION_ID Stream END
> get POdcast ran
> ```
> 
> Are you sure the request isn't being triggered twice? Try logging whenever the `'/track/:url(*)` route gets called.

So I took your advice and added 

```
router.get('/track/:url(*)', (req, res) =>{
    var url = req.params.url.substr(0); 
    console.log('/track/'+url);
```

and yes for some reason chrome and other browsers are requesting it twice.

**Comment by tomas** [comment]
Not that I think of now, sorry. :)
