### ISSUE TITLE
done event never getting fired!!!

### ISSUE THREAD

**Issue by sherebiahtishbi** [tomas/needle#313]
Hi I am downloading an mp3 file using needle and below is the code. File is successfully downloaded but done event never fired. 

```
var out = fs.createWriteStream(filepath);
var options = { follow_max :5 }
needle.get(downloadUrl,options)
            .pipe(out)
            .on('done', function(err){
                console.log('Download complete...');
            });
```

**Comment by JiPaix** [comment]
Hi, fs has no `'done'` event, using `'close'` as documented [here](https://nodejs.org/api/fs.html#fs_event_close_2) solves your problem

**Comment by sherebiahtishbi** [comment]
Thanks Ji! Documentation says "done" is former "end"! Anyways will try and see how it goes. But by all means this is my goto library for most of my need.

**Comment by JiPaix** [comment]
in addition to this:  

You can either have your code executed from needle `done` event or fs `close` event like this:
```js
needle
  .get(downloadUrl, options)
  //=> this is a needle event
  .on("done", function(err) {
    console.log('Download complete...');
  })
  //=> pipe to fs
  .pipe(out)
  // fs takes over
  //=> this is an fs close event
  .on("close", function() {
    console.log("File writing complete...");
  })
```

Not using chaining makes it less confusing handling errors and events

```js
const request = needle.get(downloadUrl, options);
request.pipe(out);
// not chaining is important here
request.on("error", function() {
  // error with needle
});
out.on("error", function() {
  // error with fs
});
request.on("done", function() {
  // done with needle
});
out.on("close", function() {
  //done with fs
});
```

**Comment by sherebiahtishbi** [comment]
That's really helpful, thank you. Will be implementing soon. Thank you
again for that fs close suggestion! Much appreciated.

Regards
Sherebiah

**Comment by sherebiahtishbi** [comment]
All good! it works as a charm!
