### ISSUE TITLE
Version 2.4.1 or 2.5.0 ?

### ISSUE THREAD

**Issue by Xubor** [tomas/needle#322]
Why npm shows as actual version 2.5.0 , while here in repository in package.json is stated version 2.4.1 ? What is the difference and why it is this way?

npmjs:
![Capture](https://user-images.githubusercontent.com/4212732/84526500-b43f0400-acdd-11ea-9d4a-63a83d3f1b0b.PNG)

github:
![Capture](https://user-images.githubusercontent.com/4212732/84526654-097b1580-acde-11ea-9b12-433c19c0f8df.PNG)

**Comment by tomas** [comment]
I forgot to push tags, that's all. Just updated them now.

**Comment by Xubor** [comment]
Wow, there was tricky "downgrade" 2.4.0 -> 2.3.2  on 3.2.2020. Probably mistake? This should never happen, as local npm would not upgrade to lower version.

...please, create CHANGELOG.md and keep all information about changes there !

**Comment by tomas** [comment]
Probably some weirdness due to patches/branches being applied. Nothing to worry. :)
