### ISSUE TITLE
Needle@2.5.2 not published

### ISSUE THREAD

**Issue by JackuB** [tomas/needle#331]
Hi, saw this comment https://github.com/tomas/needle/pull/326#issuecomment-685016854 about publishing 2.5.2. But the 2.5.2 is not available on npm. _Latest_ is still the deprecated 2.5.1. Which leads to npm showing:

> This package has been deprecated

<img width="1240" alt="screenshot_2020-09-01_at_23 27 59" src="https://user-images.githubusercontent.com/1788727/91913661-6e7b5180-ecb6-11ea-8f50-a4d000b6749a.png">

And `npm i needle@latest` installing the deprecated version.

<img width="914" alt="Screenshot 2020-09-02 at 0 52 43" src="https://user-images.githubusercontent.com/1788727/91913744-9ec2f000-ecb6-11ea-8982-5ad5b27b7f43.png">

**Comment by tomas** [comment]
Oops, forgot to push updated version. Please try again now!
