### ISSUE TITLE
Support env HTTP_PROXY, HTTPS_PROXY

### ISSUE THREAD

**Issue by cgcnrdpd** [tomas/needle#336]
Hello, I'm using https://github.com/Viber/viber-bot-node and the lib is using this lib, but your lib doesn't support proxy in env. Could you update your lib to support HTTP_PROXY and/or HTTPS_PROXY. Thank you so much!

**Comment by TimothyJones** [comment]
I would also like this!

**Comment by tomas** [comment]
Sure, no problem. Anyone would like to submit a PR for this?

**Comment by robotoer** [comment]
Would love to also have support for the `NO_PROXY` env var as well!
