### ISSUE TITLE
captialized 'GET' is not accepted as a readable verb

### ISSUE THREAD

**Issue by erf** [tomas/needle#364]
captialized 'GET' is not accepted as a readable verb, so it expected a "data" object. 

I would think you could write:
```
	const res = await needle('GET', uri, params)
```

where, params has a header with authentication, but this fails

instead i have to write:
```
	const res = await needle('get', uri, params)
```

I would think http verbs "get" and "GET" were case-insensitive, as per standard

**Comment by tomas** [comment]
Yes I think you're right. We should change this. Do you have time to submit a PR?

**Comment by erf** [comment]
I can give it a go.
