### ISSUE TITLE
why not let needle.get return a promise if no callback is given?

### ISSUE THREAD

**Issue by erf** [tomas/needle#365]
Why not let needle.get return a promise if no callback is given?

Then i could simply do:
```
	const res = await needle.get(uri, params)
```

**Comment by tomas** [comment]
Yes, also right. Do you have time for a PR? :)

**Comment by erf** [comment]
Will try :)

**Comment by erf** [comment]
I'd like to help, but I'm a little hesitant as i have not done a lot of javascript work in a while, and i don't know your codebase well, but i can try if i find time.
