### ISSUE TITLE
Memory leak when a stream in the pipeline gets destroyed unexpectedly

### ISSUE THREAD

**Issue by alolis** [tomas/needle#368]
Hello,

### Background

We are using `needle` in one of our projects and we have noticed a slow but steady increase in the tcp memory buffers. The linux command used to view the tcp memory pages allocation is `cat /proc/net/sockstat`. 

Every time we killed the service, the memory consumption dropped significantly so we started digging.

Before kill:

<img width="452" alt="before_kill" src="https://user-images.githubusercontent.com/82233/127516490-33e80aeb-2a2a-4b23-b589-89c7fc1559ff.png">

After kill:

<img width="400" alt="after_kill" src="https://user-images.githubusercontent.com/82233/127516509-f2a9f131-f0b9-47a7-a057-281b2b37a21e.png">

After plenty of tests we started noticing that the needle streams we use, do not fire the `close` event. Now, I am not sure where exactly the problem is, but if the `close` event does not fire, it means that the underlying resources have not been destroyed. If they are not getting destroyed than that is consistent with the tcp memory pages increase we have been seeing.

### How to reproduce

The following sample code shows the problem:

```
const needle = require('needle');
const {pipeline} = require('stream');
const {createWriteStream} = require('fs');

const url = 'https://releases.ubuntu.com/21.04/ubuntu-21.04-desktop-amd64.iso.torrent';

const readStream = needle.get(url);

readStream.on('end', () => console.log('needle END event fired')); // FIRES JUST FINE
readStream.on('close', () => console.log('needle CLOSE event fired')); // DOES NOT FIRE

const writeStream = createWriteStream('ubuntu-21.04-desktop-amd64.iso.torrent');

pipeline(readStream, writeStream, (error) => {
  if (error) {
    console.log(error);
  }

  // By uncommenting the next line, the CLOSE event WILL fire, but it shouldn't be required.
  // readStream.destroy();
});
```

### Environment

`node.js version: v12.16.1`
`needle version: v2.8.0`

Please let me know if I can help in any other way to get to the bottom of this. Thank you for your time.

**Comment by tomas** [comment]
Hmmm, this is indeed strange. Are you using the 'close' event to trigger a specific behaviour to perform additional actions on the stream or connection?

**Comment by alolis** [comment]
Hi @tomas 

No, we are not doing anything else after that. The 'close' event is not used at all in our production, I've only added it for debugging purposes to figure out what was going on with the tcp memory increase.

The flow of the actual code is very similar to the sample code I gave you above.

**Comment by tomas** [comment]
What options are you using regarding the connection? `Connection: keep-alive`? 

Also, does this also happen on earlier versions of Node or Needle?

**Comment by alolis** [comment]
I am running the sample code above as-is without any changes with `node main.js` and I reproduce the problem. No extra connection options.

I was able to reproduce it with `needle v2.4.0` and `needle v2.5.2` as well. 

The problem is reproducible with `node.js v10.16.0` as well from a test run a just did.

**Comment by tomas** [comment]
I see. I'll take a look at this later today. But you certainly shouldn't have to destroy the stream manually. 

I'm thinking it might have to do with [this](https://github.com/tomas/needle/blob/master/lib/needle.js#L749-L752) (if you want to fiddle with the code right away).

**Comment by alolis** [comment]
Thanks! I will have a look at the link you provided as well.

**Comment by alolis** [comment]
Hey @tomas. Did you have a chance to look at this the other day?

I am looking at [this](https://github.com/tomas/needle/blob/cfc51beac3c209d7eeca2f1ba546f67d9aa780ea/lib/needle.js#L499) line and I am wondering why are you calling `this.destroy` manually here? Shouldn't the socket close automatically as soon as it receives the `FIN` packet?

**Comment by tomas** [comment]
That is meant to handle unexpected errors in the underlying socket. Take a look at [this test](https://github.com/tomas/needle/blob/master/test/long_string_spec.js) for an example.

Does removing that line fix the issue, by the way?

**Comment by alolis** [comment]
Hey @tomas ,

Sorry for the small delay.

So, I run the test again with `DEBUG=needle* node main` and the following is the full debug output:

```
DEBUG=needle* node main.js
  needle Making request #1 {
  localAddress: undefined,
  lookup: undefined,
  protocol: 'https:',
  host: 'releases.ubuntu.com',
  port: 443,
  path: '/21.04/ubuntu-21.04-desktop-amd64.iso.torrent',
  method: 'get',
  headers: {
    accept: '*/*',
    'user-agent': 'Needle/2.7.0 (Node.js v12.16.1; darwin x64)',
    host: 'releases.ubuntu.com'
  }
} +0ms
  needle Got response 200 {
  date: 'Thu, 05 Aug 2021 14:27:27 GMT',
  server: 'Apache/2.4.29 (Ubuntu)',
  'last-modified': 'Thu, 22 Apr 2021 14:43:25 GMT',
  etag: '"34978-5c090b3a9db31"',
  'accept-ranges': 'bytes',
  'content-length': '215416',
  connection: 'close',
  'content-type': 'application/x-bittorrent'
} +523ms
MAIN.JS END event fired <==== This is console.log from main.js 
  needle on_socket_end returned: 1, this.writeable: undefined, this.destroyed true +515ms <== This is an extra debug msg I added
```

So the last two lines on the log above indicate that the END event is fired normally and the code block from [here](https://github.com/tomas/needle/blob/cfc51beac3c209d7eeca2f1ba546f67d9aa780ea/lib/needle.js#L498) does NOT execute, which from what I understand is the correct behavior unless something really unexpected has happened. 

However, I did force line block to execute (which means that `this.destroy` was called) and the CLOSE event still does not fire. Full debug run:

```
 DEBUG=needle* node main.js
  needle Making request #1 {
  localAddress: undefined,
  lookup: undefined,
  protocol: 'https:',
  host: 'releases.ubuntu.com',
  port: 443,
  path: '/21.04/ubuntu-21.04-desktop-amd64.iso.torrent',
  method: 'get',
  headers: {
    accept: '*/*',
    'user-agent': 'Needle/2.7.0 (Node.js v12.16.1; darwin x64)',
    host: 'releases.ubuntu.com'
  }
} +0ms
  needle Got response 200 {
  date: 'Thu, 05 Aug 2021 14:34:31 GMT',
  server: 'Apache/2.4.29 (Ubuntu)',
  'last-modified': 'Thu, 22 Apr 2021 14:43:25 GMT',
  etag: '"34978-5c090b3a9db31"',
  'accept-ranges': 'bytes',
  'content-length': '215416',
  connection: 'close',
  'content-type': 'application/x-bittorrent'
} +512ms
MAIN.JS END event fired <==== This is console.log from main.js 
  needle Request error Error: Remote end closed socket abruptly.
    at TLSSocket.on_socket_end ('./needle/lib/needle.js:500:17)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) +498ms
  needle Already finished, stopping here. +0ms
```

> Does removing that line fix the issue, by the way?

Nope, I removed the whole block, and seems to do nothing.

```
   // if (!socket.on_socket_end) {
  //   socket.on_socket_end = on_socket_end;
  //   socket.once('end', function() { process.nextTick(on_socket_end.bind(socket)) });
  // }
```

**Comment by alolis** [comment]
Hm, I see that you are using a [`PassThrough`](https://github.com/tomas/needle/blob/cfc51beac3c209d7eeca2f1ba546f67d9aa780ea/lib/needle.js#L306) stream underneath, which is a [transformer stream](https://nodejs.org/api/stream.html#stream_implementing_a_transform_stream) and those do not emit `close` event.

**Comment by tomas** [comment]
Ahh yes, indeed. But why would that trigger the memory increase you're seeing then?

**Comment by alolis** [comment]
> Ahh yes, indeed. But why would that trigger the memory increase you're seeing then?

Oh man...goodbye sleep...I will investigate some more...

**Comment by alolis** [comment]
@tomas , can you please help me understand [this](https://github.com/tomas/needle/blob/master/lib/needle.js#L619)? 

Why is a new pipe created for every piece in `pipeline` array?

**Comment by alolis** [comment]
I think I got it but I want to make 100% sure so I will update you in the morning. I need to re-run everything with a clear head!

**Comment by tomas** [comment]
Sure thing!

**Comment by alolis** [comment]
Hey @tomas,

Sorry for the delay but I was trying to get to the bottom of this.

So, the memory leak is real. If the readable stream, for some reason gets destroyed before properly ending, then the following error occurs:

```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
        at ServerResponse.onclose (internal/streams/end-of-stream.js:80:15)
        at ServerResponse.emit (events.js:323:22)
        at ServerResponse.EventEmitter.emit (domain.js:482:12)
        at Socket.onServerResponseClose (_http_server.js:209:44)
        at Socket.emit (events.js:323:22)
        at Socket.EventEmitter.emit (domain.js:482:12)
        at TCP.<anonymous> (net.js:668:12)
```

However, the above will not trigger an 'error' event which means that all the streams that were [piped](https://github.com/tomas/needle/blob/cfc51beac3c209d7eeca2f1ba546f67d9aa780ea/lib/needle.js#L618), will be left hanging. 

One solution is to use `stream.pipeline` instead of `.pipe` which handles the above error automatically, plus, proper cleanup of the whole pipeline. With the changes I did in [this pull request](https://github.com/tomas/needle/pull/370), the tcp memory goes back to 0 even when an `ERR_STREAM_PREMATURE_CLOSE` occurs. 

I did try to see if I can make it work without using `stream.pipeline` by using the `IncomingMessage` 'aborted' and 'error' events on the [`resp`](https://github.com/tomas/needle/blob/cfc51beac3c209d7eeca2f1ba546f67d9aa780ea/lib/needle.js#L505) object like so:

```javascript
var request = protocol.request(request_opts, function(resp) {
   resp.on('aborted', function() {
     // Did not fire on premature close error
   });    

   resp.on('error', function(error) {
     // Did not fire on premature close error
   });

   resp.on('close', function() {
     // Did fire so perhaps some error handling can be made here by checking this.destroyed ?
   });

    .....code
}
```

Based on the documentation [here](https://nodejs.org/api/http.html#http_http_request_options_callback) the above events should have fired:

```
In the case of a premature connection close after the response is received, the following events will be emitted in the following order:

'socket'

'response'

'data' any number of times, on the res object

(connection closed here)

'aborted' on the res object

'error' on the res object with an error with message 'Error: aborted' and code 'ECONNRESET'.

'close'
  'close' on the res object
```

I have also searched to see if anyone else has seen a similar issue and found [this](https://github.com/nodejs/web-server-frameworks/issues/41) and [this](https://github.com/nodejs/node/pull/33172). Unfortunately, like I said above, the event handlers did not fire so I might be missing something from within the needle code that affects the listeners.

Feel free to free to do your own tests as well and to check my [pull request](https://github.com/tomas/needle/pull/370) to see the exact changes I am referring to. Let me know how do you want to handle this so we can try and fix it!

**Comment by tomas** [comment]
Wow, you really DID get to the bottom of it! Kudos! 

I'm a bit busy now but will take a look later.

**Comment by alolis** [comment]
Issue #280 from 2019 is basically the same problem but reproduced in a different way.  Basically, if a stream in the pipeline gets destroyed before ending properly, a memory leak happens. You can also reproduce the `ERR_STREAM_PREMATURE_CLOSE` if you use the following sample code:

```javascript
const needle = require('needle');
const {pipeline} = require('stream');
const {createWriteStream} = require('fs');

var url = 'SOME BIG ASS REMOTE FILE URL';
const writeStream = createWriteStream(`./out.dat`);

pipeline(readStream, writeStream, (error) => {
   if (error) {
     console.log(error);
   }
 });

setTimeout(function () {
  console.log("destroying write stream...");
  writeStream.destroy();
}, 2000);

setInterval(function () {
  // Keep alive
}, 3000);
```

I have also updated the title of this issue because it was misleading.

**Comment by alolis** [comment]
Since this is a serious issue and has been affecting us severely I have pushed my branch to production after further testing yesterday and I can confirm that tcp memory usage seems to be very low now, as expected.

Looking forward to the officially fixed version ;)
