### ISSUE TITLE
a ':' in nonce breaks digest authentication

### ISSUE THREAD

**Issue by jvanvorst** [tomas/needle#415]
Server sends:
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Digest realm="IP Camera", charset="UTF-8", algorithm="MD5", nonce="636144c2:2970b5fdd41b5ac6b669848f43d2d22b", qop="auth"

needle responds with:
authorization: Digest uri="xxxxx", realm="IP Camera", **nonce="636144c2"**, username="xxxx", response="42289c79a16ff73462e953b661d0a2d5", qop="auth", nc="00000002", cnonce="49f6a75e"

**Comment by tomas** [comment]
Fixed in aa49d75. Thanks!
