### ISSUE TITLE
Detect encoding from HTML/XML <meta> header

### ISSUE THREAD

**Issue by leesei** [tomas/needle#45]
Some server does not notify charset in HTTP header, it's better to also sniff from the HTML/XML `<meta>` header.

I've done so using [charset](https://github.com/fengmk2/charset).
```js
var encoding = 'utf8';  // defaults to 'utf8'
if (opts.encoding) {
  encoding = opts.encoding;
  console.info("Using encoding from options: " + encoding);
}
else {
  // detect charset from header or body (the first 1Kb)
  var cs = charset(res.headers, body.toString('utf8', 0, 1024));
  if (cs) {
    encoding = cs;
    console.info("Detected encoding: " + encoding);
  }
}
var str = iconv.decode(body, encoding);
```

**Comment by leesei** [comment]
I was studying the latest code and didn't realize the code in `decoder.js` was added because of me :stuck_out_tongue:.

**Comment by fritx** [comment]
heys @tomas how about using [jschardet](https://www.npmjs.com/package/jschardet) for charset auto-detect, if charset 'not found' in '<meta>'?
at https://github.com/tomas/needle/blob/master/lib%2Fneedle.js#L105
