### ISSUE TITLE
Default charset set to UTF-8 and charset is not always the second param of header

### ISSUE THREAD

**Issue by thanh-nguyen** [tomas/needle#60]
ISO-8859 was the default of HTML4 but now it's UTF-8 for HTML5. I think it's a better idea now to set default charset to UTF-8. Besides, when detecting charset in parse_content_type(), charset is not always the second param. So it's a better to match it agains the whole header.

```javascript
  parse_content_type: function(header) {
    if (!header || header == '') return {};

    var charset = 'utf-8';
    var arr = header.split(';');
    try { charset = header.match(/charset=([^;]+)/)[1] } catch (e) { /* not found */ }

    return { type: arr[0], charset: charset };
  },
```

**Comment by tomas** [comment]
It's been very very long since this. I'm closing this issue, but feel free to reopen once you have more information about this. I'd prefer to rely any changes on the W3 spec rather than an independent website.
