### ISSUE TITLE
Digest Auth Fails

### ISSUE THREAD

**Issue by shaneseaton** [tomas/needle#67]
Not 100% sure, but when I was using this against the moodstock API, the digest auth was failing. I am pretty sure it was because the first authorisation response is setting nc=2 instead of 1. I simply set the nc to be 0 in the digest.generate function and it all worked fine for me.

**Comment by tamaspiros** [comment]
Have there been any updates on this? I'd love to get the digest auth working

**Comment by tomas** [comment]
This is great news. I'll try it out in a sec.

**Comment by tomas** [comment]
Ok so after chaging the method to uppercase letters in `lib/auth.js`, the above example against httpbin still didn't work. I revised the header parsing and some other things and eventually got it to work against the test endpoint at test.webdav.org.

```
var needle = require('..');
var opts = {
  username: 'user1', 
  password: 'user1',
  auth: 'digest'
}

needle.get('http://test.webdav.org/auth-digest/', opts, function(err, resp) {
  console.log(err, resp.statusCode, resp.headers, resp.body);  
})
```

This is currently on the [digest-auth-fixes](https://github.com/tomas/needle/tree/digest-auth-fixes) branch. @montanajob can you try and see if using that code it (still) works so I get it merged to master? 

And thanks again!

**Comment by tomas** [comment]
And I finally figured out the reason why the test against httpbin wasn't working. Turns out they expect [cookies to be returned](https://github.com/Runscope/httpbin/issues/124) (which isn't actually part of the spec).

**Comment by montanajob** [comment]
Yes, the digest-auth-fixes branch still works for me.  Thanks for the fix.
