### ISSUE TITLE
timeout not work

### ISSUE THREAD

**Issue by michael2043** [tomas/needle#84]
I use 
needle.get('some url'
,{"timeout":20000,"headers"  : {"Depth" : "1", "Content-Type": 'text/xml; charset="utf-8"'}}
,function(err,res){
       ....do something....
}).pipe(out);

when downloading large file and network Interrupt，callback is not fired.and timeout is not working too.

**Comment by tomas** [comment]
Needle already handles open_timeout vs read_timeout. Try them out and let me know if it works (closing this issue, but feel free to reopen if it's not working as expected).
