### ISSUE TITLE
Integers in JSON are converted to strings

### ISSUE THREAD

**Issue by ancasicolica** [tomas/needle#91]
I sent a POST request using needle like this:

```javascript
needle.post(SERVICE_SOCKET + '/verify',
          {
            message: {
              value1: 1.2456,
              value2: -100,
              value3: 100,
            }
          },
          {},
          function (err, resp) {
            done(err);
          });
```

The receiver then got an object like this:
```javascript
{
  value1: '1.2456',
  value2: '-100',
  value3: '100'
}
```

But I was expecting the following (as I get it using restify):
```javascript
{
  value1: 1.2456,
  value2: -100,
  value3: 100
}
```

As we are using both needle and restify clients I have to handle both data formats which is quite dissatisfying. Am I missing an option or is this a bug?

**Comment by tomas** [comment]
Try passing a `json: true` in the options. Needle is querystringifying your message object, which results in integers being treated the same way as strings.

``` js
needle.post(url, data, { json: true }, function(err, resp) { ... });
```

**Comment by ancasicolica** [comment]
Thanks, this solved the problem.

I suggest to enhance the following entry in the readme document as it wasn't obvious for me:

`json` : When true, sets content type to `application/json` and sends request body as JSON string, instead of a query string. __This is mandatory if you are using numbers in your JSON structures.__
