### ISSUE TITLE
primitive in post response returns empty string

### ISSUE THREAD

**Issue by futurechan** [tomas/needle#94]
I am calling a restful service that return ```true``` or ```false``` in the response body. When I receive this response, it is an empty string. I can call ```String(resp.raw)```, but I feel like a primitive that is not enclosed in an JSON object should be accepted as it works with JSON.parse. I'm using 0.7.10.

**Comment by tomas** [comment]
What content type is the endpoint returning?

**Comment by futurechan** [comment]
@tomas application/json

**Comment by tomas** [comment]
So the raw response is a single "true" or "false" string?

**Comment by futurechan** [comment]
yes, the response is a single "true" or "false" string.

**Comment by tomas** [comment]
That's odd. By default needle parses the output stream, so it should be doing a `JSON.parse("true")` that should return `true`. Any other pointers?

**Comment by futurechan** [comment]
@tomas I'm just guessing here:

It look like https://github.com/tomas/needle/blob/master/lib/needle.js#L334 evaluates to false, so https://github.com/tomas/needle/blob/master/lib/needle.js#L339 never happens.

**Comment by tomas** [comment]
Hmm, I don't think so. Those chunks should be buffers so no this.read() should never be "false" nor falsy. 

Let me try a quick test and I'll get back to you.

**Comment by tomas** [comment]
Ok, quick test works. Something else is going on.

``` js
var http   = require('http'),
    needle = require('./');

http.createServer(function(req, res) {
  res.writeHead(200, {'Content-Type': 'application/json' });
  res.end('true');
}).listen(function() {
  var port = this.address().port;
  needle.get('localhost:' + port, function(err, resp) {
    if (resp.body === true) {
      console.log('Got boolean!');
    } else {
      console.log('Invalid type: ' + resp.body.constructor);
    }
  })
});
```

**Comment by futurechan** [comment]
In my case, ```chunk = this.read()``` did evaluate to false. Any idea why?

**Comment by tomas** [comment]
AFAIR this.read() returns false when there's no more data to read.

**Comment by futurechan** [comment]
@tomas try your example with 'false' instead of 'true'.

var http   = require('http'),
    needle = require('./');

http.createServer(function(req, res) {
  res.writeHead(200, {'Content-Type': 'application/json' });
  res.end('false');
}).listen(function() {
  var port = this.address().port;
  needle.get('localhost:' + port, function(err, resp) {
	  console.log('resp.body: ' + resp.body);
    if (resp.body === false) {
      console.log('Got boolean!');
    } else {
      console.log('Invalid type: ' + resp.body.constructor);
    }
  })
});

**Comment by tomas** [comment]
Holy shmoly, looks like you're right. This is a scenario that the `while(chunk = this.read())` strategy doesn't seem to cover. But even the official documentation says do it that way!

**Comment by futurechan** [comment]
@tomas I'm thinking a simple null check is all that's needed. If you agree, I'll issue the PR.

**Comment by tomas** [comment]
Sure, send it over.

**Comment by tomas** [comment]
(Be sure to add a test for it!)

**Comment by futurechan** [comment]
I pulled down the repo and ran the tests as is and got a few errors. Is that expected?

**Comment by futurechan** [comment]
@tomas I issued PR #96 
It works, but I noticed the body was ```'false'``` and not ```false```. Is that expected?

**Comment by tomas** [comment]
Nice work there @futurechan. 

Body _should_ be `false`, not `'false'`. Does that happen on the example above too?

**Comment by futurechan** [comment]
In the above example ```(resp.body === true)``` worked. Perhaps there's another truthy/falsey check that's failing.

**Comment by tomas** [comment]
Apparently. But with your null check does the example work with === false?

**Comment by futurechan** [comment]
No, it looks like 'false' is returned. I'm working on two other things ATM. I'll try to circle back ASAP.

**Comment by futurechan** [comment]
@tomas 

[Line 357 is evaulating to true](https://github.com/tomas/needle/blob/master/lib/needle.js#L357), so we are calling .toString(), which is why ```'false'``` is returned instead of ```false```. Any pointers?

**Comment by tomas** [comment]
I'm thinking that [resp.body[0] in line 350](https://github.com/tomas/needle/blob/master/lib/needle.js#L350) is `false` which means that the evaluation returns false when in fact it should evaluate to true.

What happens if we change `if (resp.body[0] && !Buffer.isBuffer(resp.body[0])) {` to `if (resp.body[0] !== null && !Buffer.isBuffer(resp.body[0])) {`?

**Comment by futurechan** [comment]
Of course! I'll touch up the PR in just a sec.

**Comment by futurechan** [comment]
@tomas all fixed up! I may be wrong, but iit looks like ```null``` is a valid response that also does not work.

**Comment by tomas** [comment]
Then I guess we should go all the way with `resp.body[0] !== undefined`.

**Comment by futurechan** [comment]
@tomas I'm not sure what you mean, but the ```false``` condition is covered now.

**Comment by tomas** [comment]
Slick. Just merged, releasing in a few minutes.
