### ISSUE TITLE
easy response types

### ISSUE THREAD

**Issue by shenanigans** [tomas/needle#95]
What if the server's response isn't the `content-type` you were expecting? What if you want to check the content-type before you wade into the body? Right now you have to muck about in the headers manually to be sure, worrying about incidentals like `"; charset=UTF-8"`.

It would be really convenient if responses had a simple `type` property set to `"json"`, `"multipart"`, or `"xml"`. It would also be convenient to have an option when the request goes out to only bother parsing the correct content-type and pass errors otherhow.

**Comment by tomas** [comment]
I'm not sure what you mean. You'd like Needle's responses to contain a `.type` property set to the header's Content-Type?

**Comment by shenanigans** [comment]
yes, with any additional information scraped off. Since you're reading the
content-type and parsing the body selectively by type, I imagine there's a
convenient place in the code to save this handy property onto the response.
And when it gets saved, there's probably no need to save
`"application/json"` when just `"json"` will do.

**Comment by tomas** [comment]
Sounds like a good idea, but I think there are many cases in which the dev wouldn't know what to expect. For example, what do the following content types map to?

```
'application/octet-stream' # data?
'application/atom+xml' # atom or xml?
'application/font-woff' # font or woff?
```

I think it would be clearer for everyone to use the regular Content-Type. We could, though, include a response.json = true or response.xml = true whenever one of those parsers come into action. This would let you do:

``` js
if (response.json)
  console.log('JSON')
else if (response.xml)
  console.log('XML')
else if (response.type.match(/text/)
  console.log('Text response')
else
  console.log('Binary data')
```

**Comment by shenanigans** [comment]
Yeah, I like that idea: standard Content-Type and boolean props for the common parsers. And like I said initially, it would be nice to avoid parsing anything I'm not expecting with a request option.
```javascript
needle.get (
  resourcePath,
  { contentType:'application/json' },
  function (err, response) {
    // if there's no err, we got json
  }
);
```

**Comment by tomas** [comment]
Ok mister, just landed in c3cd16ea2077b872a00c8f7a90b267543718316c. Needle's responses will now contain a `parser` property that can be either `json` or `xml` if one of those parsers was used. If parsing fails for any reason, the property will not be there.

If not using callback, the returned stream will also contain the `parser` property, however in that case it may occur that the parsing fails and the resulting data is not an object as you would expect.

As for the "don't parse stuff I'm not interested in", I think it makes sense to map it some way to the `accept` option. Eg. if you say: `accept: application/json` only `application/json` responses will be parsed -- but it's not as simple as it sounds, though. What happens if one accepts `application/xml` but the server replies with `test/xml`?

**Comment by shenanigans** [comment]
That all sounds great. I like the idea of using the `accept` option except that it's not a desirable behavior in all cases, so maybe a Boolean option to turn it on. `restrictType:true` or something. You could potentially go with `strict:true` as a general Boolean for turning all response filters on and off, if you can see yourself thinking up more response filters.

**Comment by tomas** [comment]
What about simply passing `{ parse: 'application/json' }` instead of `true`? 

And why wouldn't you want to parse other content types, by the way?

**Comment by shenanigans** [comment]
Your second question made me realize my first answer doesn't address my own situation. A String `parse` property is actually **necessary** but it should accept the same Strings held in the new `parser` property and not proper content types. My specific example would be `{ accept:'application/schema+json', parse:'json' }`.

**Comment by shenanigans** [comment]
re: why, my JSON Schema validator is designed to handle foreign schemata which may be incorrect or even hostile. I don't want it wasting cpu resources parsing a bad response.

**Comment by tomas** [comment]
Makes sense. Now with the new parser property this should be trivial. A beer or two tonight might pull the trick.

**Comment by shenanigans** [comment]
Thanks, enjoy!

**Comment by tomas** [comment]
Took a bit longer than expected, but 7380884 makes the parse/parse_response option accept 'json' or 'xml'.

Sidenote: I think this is the first time I've seen a fully numeric short commit hash. Will this break Github? hehe

**Comment by shenanigans** [comment]
Righteous. Thanks for staying on it.
