### ISSUE TITLE
multipart and UTF8 characters

### ISSUE THREAD

**Issue by kennyhk** [tomas/needle#97]
When i post a file (multipart) with another key-value pair (contains UTF8 characters), my servers  got incorrect encoding.

then i see the code in multipart.js (generate_part) is :
<code>return_part += part.value</code>
the value look like in UTF8 encoding but send out with binary encoding

Finally i get the collect UTF8 characters by change to :
<code>return_part += new Buffer(part.value+'', 'utf8').toString("binary");</code>

is it a issue? 
thank you

**Comment by tomas** [comment]
It might. Can you provide an example with code so I can fix it and add a test for it?

**Comment by aidistan** [comment]
I have met the same issue and my code looks like:

```coffeescript
# CoffeeScript
require('needle').put 'http://request.lesschat.com/VJ2haycT',
  nickname: '测试1',
  data:
    value: JSON.stringify
      title: '测试2',
      version: 1,
    content_type: 'application/json'
, multipart: true
, (err, res) ->
  console.log('STATUS: ' + res.statusCode)
  console.log('BODY: ' + JSON.stringify(res.body))
```

> Request (http://request.lesschat.com/) here is an online tool that I used to catch my request.

And the request caught by Request looks like:
```
HEADERS
x-forwarded-for: 58.200.129.143
host: request.lesschat.com
x-forwarded-proto: http
connection: close
content-length: 296
accept: */*
user-agent: Needle/0.10.0 (Node.js v0.10.36; linux x64)
content-type: multipart/form-data; boundary=--------------------NODENEEDLEHTTPCLIENT 

RAW BODY
----------------------NODENEEDLEHTTPCLIENT
Content-Disposition: form-data; name="nickname"

K�1
----------------------NODENEEDLEHTTPCLIENT
Content-Disposition: form-data; name="data"
Content-Type: application/json

{"title":"K�2","version":1}
----------------------NODENEEDLEHTTPCLIENT--
```

Hope this could be fixed :smiley:
