### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GeoffreyPlitt** [tomas/needle#98]
The following code produces a memory leak. Increasing concurrency or decreasing the delay will speed it up, and vice versa-- but the memory still climbs and never comes back down. Try letting it run for an hour while looking at "htop" (or top, or a graphical memory profiler). I tried this with Node 0.10, 0.11, 0.12, in Mac and Linux. There are not stack issues, dangling variables, or closure issues as far as I can tell. I'm using Needle 0.7.11, the latest version as of this writing.

```javascript
var needle = require('needle');
var concurrency = 1;

//----- MAIN -------

var go = function() {
  needle.request('GET', 'https://google.com/', null, {}, function(err, res){
    console.log(res.statusCode);
    setTimeout(go,1000);
  });
}

for(var i=0;i<concurrency;i++) go();
```

**Comment by GeoffreyPlitt** [comment]
FYI, if you think the for loop at the bottom, or the setTimeout is the issue, it's not-- you can just replace "needle.request" with "setTimeout" and the memory leak goes away (no change to the rest of the code)

**Comment by GeoffreyPlitt** [comment]
Update: adding `{agent: false}` to the options does fix it. I've also verified this leak in io.js, with agent=false.

**Comment by tomas** [comment]
Yikes. Will take a look at this in the next few days. Thanks for reporting!

**Comment by GeoffreyPlitt** [comment]
Update: I've proved the bug a little more rigorously. add the following line and run with node's `--expose-gc` option.

```javascript
setInterval(global.gc, 10*1000);
```

The memory will still climb, slower, but it will not stop climbing if you let it go for more than a few minutes.

Replacing needle with a raw call to http.request, and using the garbage collection mechanism above, stabilizes after a minute and never climbs.

**Comment by tomas** [comment]
Hi @GeoffreyPlitt, 

Stabilizes after a minute on how much rss/heap mem usage?  .I've been trying both the raw http.request and the agent = false trick and I get very similar results. The global.gc trick does seem to help, though. How much concurrency/delay are you testing with?

**Comment by tomas** [comment]
I think I found it. Please take a look at the `rc` branch and see if you get the same behaviour. There are also a few other things in it, but the main thing was to stop using anonymous functions, and make Needle a real object (e.g. `new Needle()`) instead of it just being a plain one.

**Comment by GeoffreyPlitt** [comment]
Good stuff. I ran my test in both master and rc and you're right, on rc the memory stopped growing. Good fixes!

**Comment by tomas** [comment]
Cool. I'm closing this one given that I'm merging the branch right away.

**Comment by GeoffreyPlitt** [comment]
Can you point me to documentation about new-vs-plain objects cause memory leaks?

**Comment by tomas** [comment]
[This](http://stackoverflow.com/questions/6698386/are-there-any-drawbacks-to-using-anonymous-functions-in-javascript-e-g-memory) might help. Also, Google has a [great article](https://developers.google.com/speed/articles/optimizing-javascript?csw=1) on writing good JS code.
