### ISSUE TITLE
Pipe req.files.file.buffer to needle.post

### ISSUE THREAD

**Issue by karan-kapoor90** [tomas/needle#99]
I'm using a node server A with an entire application with its own logic etc, and want to use another node server B to handle static file uploads and file serving, much like a CDN. Hence for this purpose, I would like to stream the file content that I get on server A in the <code>req.files.file</code> to server B using a <code>needle.post</code> . How can i stream this result straight without saving it on server A? 

I think it'll require me to use pipe, but not sure how.

**Comment by tomas** [comment]
Something like this should work:

``` js
app.get('/data', function(req, res) {

  var file = req.files.file; // stream
  var opts = {}; // whatever options you want to pass

  needle.post('other.server.com/foo', file, opts, function(err, resp) {
    if (err) return res.end(err.message);

    res.end('Success');
  })

})

**Comment by karan-kapoor90** [comment]
And how do i accept the stream on Server B ?

**Comment by tomas** [comment]
Just as you'd git it on the example, I guess. The `var file = req.files.file;` part, specifically.
